### ISSUE TITLE
Is it possible to run GUI apps as nanos Unikernels?

### ISSUE THREAD

**Issue by sudhakar3697** [nanovms/nanos#1009]
TIA. Is it possible to run apps like chrome as Nanos Unikernels and forward X11 to the Host OS?.

**Comment by prologic** [comment]
Whilst anything is _technically_ possible; there's a lot of moving parts to running Chrome in a UniKernel (_whilst possible on its own_) and then accessing it over X11 forwarding which is typically done over SSH. This of course ignores the model of "single process" which is most Unikernels support.

Curiously though; What problem would you be trying to solve here whereby you want to run Chrome or some kind of Browser in a Unikernel?

**Comment by eyberg** [comment]
we have no plans on adding in any gui/interactive support no, theoretically in the far future you could envision a framebuffer like addon/module (that would not be included by default) and stream that out but as @prologic mentioned chrome is inherently multi-process to begin with and that's just not something we're going to budge on
