### ISSUE TITLE
socket_ioctl: implement FIONREAD operation

### ISSUE THREAD

**Issue by cdosoftei** [nanovms/nanos#1036]
In the process of porting [FreeSWITCH](https://github.com/signalwire/freeswitch), I need `ioctl` to support `FIONREAD` for sockets. I know the use legitimate use cases for `FIONREAD` are rare but I trust the developers of the upstream library ([sofia](http://sofia-sip.sourceforge.net/)) had a good reason for it; regardless, I like nanos's approach to running unmodified Linux binaries, so I am taking the use case for `FIONREAD` at face value.

My current naive implementation (which needs a lot more work) looks like:
```C
/* ... */
    case 0x541b: { //FIONREAD: {
        int *bytes = varg(ap, int *);
        *bytes = 0;

        if (s->incoming->count) {
            void *p = s->incoming->buf[s->incoming->read % s->incoming->size];

            if (p) {
                struct pbuf *buf = s->type == SOCK_STREAM ? (struct pbuf *)p : ((struct udp_entry *)p)->pbuf;
                if (buf) {
                    *bytes = (int)cur_buf->len;
                }
            }
        }

        net_debug("sock %d, bytes %d\n", s->fd, *bytes);

        return 0;
    }
/* ... */
```
The returned value is satisfactory for the test contents, however as soon as the read completes, the following assertion halts the unikernel:
https://github.com/nanovms/nanos/blob/49501e5eca1afedefb2dbdfea03677b8b0dda214/src/unix/thread.c#L165

```
                                                                            24 ioctl
[19.400754]  NET: socket_ioctl: sock 32, request 0x541b
[19.400954]  NET: socket_ioctl: sock 32, bytes 35
                                                                            24 direct return: 0, rsp 0x7026dffa08
                                                                            20 nanosleep_bh: start 19.397406, interval 0.000999, rem 0x0000000000000000, elapsed 0.004068, flags 0x5
                                                                            24 thread_wakeup: 24->20 blocked_on thread, RIP=0x70c5d07123
                                                                17 nanosleep_bh: start 19.384880, interval 0.015885, rem 0x0000000000000000, elapsed 0.017399, flags 0x5
                                                                            24 thread_wakeup: 24->17 blocked_on thread, RIP=0x70c5d07123
                                                                            24 recvmsg
[19.403968]  NET: recvmsg: sock 32, type 1, thread 24
[19.404218]  NET: sock_read_bh_internal: sock 32, thread 24, dest 0x0000000103e65440, len 35, flags 0x0, lwip err 0
[19.404712]  NET: notify_sock: sock 32, events 104
[19.404853]  NET: sock_read_bh_internal:    completion 0x0000000103598f00, rv 35
                                                                            24 thread_wakeup: 24->24 blocked_on (null), RIP=0x70485123c7
000000007f02fa25	(thread_wakeup + 00000000000000a5/00000000000000c0)
000000007f007b58	(recvmsg_complete + 0000000000000108/000000000000010a)
000000007f00a06f	(sock_read_bh_internal + 00000000000000ff/0000000000000452)
000000007f00a4c0	(recvmsg_bh + 0000000000000080/00000000000000bd)
000000007f0192cf	(blockq_check_timeout + 000000000000004f/0000000000000238)
000000007f009ccf	(recvmsg + 000000000000018f/000000000000029d)
000000007f026dbd	(syscall_debug + 00000000000000fd/00000000000002ee)
000000007f0002e2	(syscall_enter + 000000000000006a/0000000000000072)
0000000000000000
```
The test case is fairly complex, I'm trying to write a simple program to reliably recreate the above situation.

**Comment by cdosoftei** [comment]
While trying to recreate the issue I realized the above crash is likely unrelated to my `FIONREAD` tinkering but rather tied to the way `recvmsg` might be implemented. The code referred in the gist below is a basic echo server listening on port TCP/5060; it works fine in Linux whereas it crashes in nanos due to the above mentioned assertion when the `recvmsg` approach is used:

https://gist.github.com/cdosoftei/d3267bba31a95c999494909a5ef3b069#file-server-c-L144-L169

If you can confirm my logic, I should probably create a separate issue instead.

**Comment by wjhun** [comment]
This does look like a bug in sock_read_bh_internal / recvmsg_complete. The completion closure assumes that the calling thread was blocked, yet it can be applied in the case of a direct return. This is somewhat similar to blocking-related issues recently resolved in the unix file handling code.

Opened #1037 to track this issue.

**Comment by cdosoftei** [comment]
I'd like to propose https://github.com/nanovms/nanos/compare/master...cdosoftei:fionread as a PR addressing this issue, however I am trying to figure out the appropriate way of adding tests for this new syscall operation. Something in the spirit of [udploop.c](https://github.com/nanovms/nanos/blob/master/test/runtime/udploop.c) should work but I'd like some direction here if possible.

**Comment by francescolavra** [comment]
@cdosoftei thank you for the PR. Would you be willing to rebase it and update it to match the current code, so we can merge it?

The queue API has been changed, so in order to check whether there is incoming data available you have to use `queue_peek(s->incoming)`.
A couple more things:
- for TCP sockets, you need to check whether the socket state is TCP_SOCK_OPEN (otherwise if a socket is in listening state you may end up dereferencing a netsock structure as if it were a pbuf)
- the `while` loop that contains `buf = buf->next` should apply to both TCP and UDP sockets (in case of UDP, if there are multiple chained pbufs they are all part of the same datagram, so their length values should be summed together)

As for test code, it is not necessary, but if you want to write it you could create a test suite in a new file in the test/runtime folder (with a generic name such as netsock.c, so we could add more socket-related tests in the future) and put there a few test cases exercising the FIONREAD ioctl on sockets working with the loopback interface.
