### ISSUE TITLE
recvmsg failure on socket read direct return

### ISSUE THREAD

**Issue by wjhun** [nanovms/nanos#1037]
sock_read_bh_internal applies the stored blockq completion when the read operation has finished, even in the case of a direct return. However, the completion in the case of recvmsg (recvmsg_complete) assumes that the thread was blocked for the operation unconditionally, leading to a spurious thread wakeup and assertion failure.

Review the logic in the completion to determine whether the thread has actually blocked. In addition, adapt to using new reusable closures where possible.

related: #1036, #1019, #1020

**Comment by francescolavra** [comment]
Resolved in https://github.com/nanovms/nanos/pull/1119/commits/847780168cbe1079e6084d4924c2b52f3612601a
