### ISSUE TITLE
https://nanos.org is down

### ISSUE THREAD

**Issue by francisdb** [nanovms/nanos#1041]
```
> curl https://nanos.org
curl: (6) Could not resolve host: nanos.org
```

**Comment by eyberg** [comment]
hi @francisdb - we actually don't have a site for nanos.org - it's registered but nothing's up - maybe when we have some more content gathered that's not found on ops' website we'll create one

**Comment by francisdb** [comment]
Then I suggest removing it from the GitHub repo description
