### ISSUE TITLE
tracking aarch64

### ISSUE THREAD

**Issue by eyberg** [nanovms/nanos#1051]
super super super low priority but was interested what this looked like

target is raspberry pi 4 (model b) which has an armv8 quad-core processor && virt extensions && new gic that removes need for emulating interrupts

important to note these come as arm(6/7)vl / 32bit kernel/userland cause there seems to be some unresolved issues, so need to build your own kernel/toolchain -> https://andrei.gherzan.ro/linux/raspbian-rpi-64/

also seems sd card problems limits ram usage to 1G - that kinda really kills this deal for now but i'd imagine by the time we can take this up this won't be a limit anymore

clearly installing qemu-x86 allows us to boot existing images, although end-goal would be for us to have pass-through

* ops memory defaults are too high

* mkfs utilizes some x86 specific instructions ->

```
/tmp/ccbeetbI.s: Assembler messages:
/tmp/ccbeetbI.s:67: Error: bad instruction `lock'
/tmp/ccbeetbI.s:67: Error: bad instruction `xadd r4,[r6,#8]'
/tmp/ccbeetbI.s:227: Error: bad instruction `lock'
/tmp/ccbeetbI.s:227: Error: bad instruction `xadd r2,[r1,#8]'
```

which is necessary even for pkgs unless you manually upload && set no-rebuild

again super low priority - just some tracking notes

**Comment by francescolavra** [comment]
aarch64 support is in, closing
