### ISSUE TITLE
Building on macOS (at least) requires nasm (at least)

### ISSUE THREAD

**Issue by CraigCottingham** [nanovms/nanos#1055]
```NASM	/Users/ccottingham/Projects/nanos/output/boot/boot/service32.o
/bin/sh: nasm: command not found
make[1]: *** [/Users/ccottingham/Projects/nanos/output/boot/boot/service32.o] Error 127
make: *** [boot] Error 2
```

There is a recipe available via Homebrew called `nasm` that looks like it might be what this is expecting:

```~/Projects/nanos % brew info nasm
nasm: stable 2.14.02 (bottled), HEAD
Netwide Assembler (NASM) is an 80x86 assembler
https://www.nasm.us/
```

I'll install it and see if it fixes this problem. If it does, I'll open a PR for `README.md`.

**Comment by CraigCottingham** [comment]
Now I get

```
LD	/Users/ccottingham/Projects/nanos/output/boot/bin/stage2.elf
/bin/sh: x86_64-elf-ld: command not found
make[1]: *** [/Users/ccottingham/Projects/nanos/output/boot/bin/stage2.elf] Error 127
make: *** [boot] Error 2
```

I'm going to try installing `i386-elf-binutils` and possibly other ELF-related recipes.

**Comment by CraigCottingham** [comment]
Okay, I just noticed that the Nanos build is looking for an `x86_64` loader, and I suspect that `i386-elf-binutils` doesn't provide that. I'm going to try tracking down an x86_64 toolchain next.

**Comment by CraigCottingham** [comment]
I found `sevki/gcc_cross_compilers`, tapped it, and tried installing `x86_64-elf-gcc`. It failed building `binutils`. I'm punting for now, until I get some guidance on how to install a toolchain that works.

**Comment by eyberg** [comment]
yes nasm is a requirement and I think the toolchain you want is avail via:

```
brew tap nanovms/homebrew-x86_64-elf
brew install nanovms/x86_64-elf/x86_64-elf-binutils
```

we only support (and will only support) building 64bit targets

also - while you're at it might as well grab the latest qemu (default qemu brew is old and has several issues)

```
brew tap nanovms/homebrew-qemu
brew install nanovms/homebrew-qemu/qemu
```

if this works for you feel free to open a PR w/updated instructions or maybe even a install script or something

**Comment by CraigCottingham** [comment]
@eyberg Thanks for the taps and packages. I get farther with `make run` now, but it's still erroring out:

```
GO	/Users/ccottingham/Projects/nanos/output/test/runtime/bin/webg
MKFS	image
metadata (children:(webg:() lib:(children:(x86_64-linux-gnu:(children:(libpthread.so.0:() libc.so.6:())))) etc:(children:(ld.so.cache:())) lib64:(children:(ld-linux-x86-64.so.2:())) kernel:()) arguments:(0:webg 1:longargument) program:/webg environment:(PWD:password USER:bobby))
couldn't stat file /lib/x86_64-linux-gnu/libpthread.so.0: No such file or directory
make: *** [image] Error 2
```

**Comment by CraigCottingham** [comment]
Unrelated: Lines 80-90 of `boot/Makefile` assume that if you're running on macOS, you don't have GNU coreutils installed, so the flags for the `stat` command aren't correct. That's a relatively simple fix, which I'll include in any upcoming PR.

**Comment by eyberg** [comment]
looks like you are trying to run webg under osx? that should be producing a statically linked version of go if built there w/GOOS=linux - so that's why that's failing - it should be fine under linux;  if you are just trying to do the fastest thing for hello world [ops](https://github.com/nanovms/ops) && https://ops.city might be what you are looking for as you don't have to do any of this, building nanos from source is really only for those wishing to hack on nanos source proper

**Comment by CraigCottingham** [comment]
@eyberg Thanks for that clarification. After going back and rereading `README.md`, I realize that right there in the first sentence under "Building/Running" it tells me to use `ops` to simply run a unikernel, which is all I was trying to do for starters. I'll take full responsibility for that, though I'll try to think of text to add to make it more obvious for anyone following who thinks like I did.

However, the same file _does_ say

> You can build and run on mac and linux

which does not appear to be the case at the moment. I'm willing to do at least some of the heavy lifting to get the build process on macOS working and documented, but I'll need some hand-holding to get through problems like the last one I pasted above.

On the other hand, if you don't actually intend to support building on macOS in the future, that's fine too. `README.md` should be changed to reflect that if so.

**Comment by wjhun** [comment]
@CraigCottingham With a few exceptions, the nanos kernel builds and runs under macOS. The readme does need some updating but, for the time being, you can refer to the build rules in the Circle CI scripts, located in .circleci/config.yml. Please refer to the "build-mac" rule and the "run" rules under "steps." The process is, essentially:

- install homebrew via:
```
CI=1 /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
```

- update homebrew formulae and install the prerequisite tools:
```
brew update && brew install nasm go wget ent
brew tap nanovms/homebrew-x86_64-elf
brew install x86_64-elf-binutils
brew tap nanovms/homebrew-qemu
brew install nanovms/homebrew-qemu/qemu
```

- download a chroot environment (based on debian 9) from which shared libraries can be sourced for image building:
```
mkdir target-root && cd target-root && wget https://storage.googleapis.com/testmisc/target-root.tar.gz && tar xzf target-root.tar.gz
```

... or build your own chroot image using the following steps:

https://github.com/nanovms/nanos/wiki/chroot-build-steps-on-debian

- now you should be able to build the kernel and run the tests:
```
export NANOS_TARGET_ROOT=target-root
make
make test
```

If hypervisor framework isn't available, add "-noaccel" to the run and test rules to run with full emulation in qemu (TCG):

```
make test-noaccel
```

A few caveats for e2e tests on darwin: running with the last few releases of Xcode causes the test for ruby to fail, as the flags for gem have changed ("--no-rdoc" is no longer valid; "-N" must be used instead). Additionally, the rust test is skipped under darwin, as cross-compilation is not yet supported.

**Comment by eyberg** [comment]
adding instructions via https://github.com/nanovms/nanos/pull/1087
