### ISSUE TITLE
graceful shutdowns on gcp (ACPI Power Off signal handling)

### ISSUE THREAD

**Issue by ssttevee** [nanovms/nanos#1065]
VMs on GCP are killed forcefully after timing out when being stopped or deleted. I have not tried on AWS.

According to [the docs](https://cloud.google.com/compute/docs/instances/stop-start-instance), an ACPI Power Off signal is sent to the guest os.

I tried this using ops with the latest release of nanos as well as the latest commit https://github.com/nanovms/nanos/commit/11be3e189560ed1b881f20adb016377126aa5897.

EDIT: Necessarily, the VM also does not shutdown after the program exits.

**Comment by eyberg** [comment]
ah, i see what you were asking, that pr you're referencing wasn't supposed to address a graceful poweroff - it's an option to reboot on an explicit failure

we can def. look into adding support for graceful shutdowns from doing something like ```ops instance stop```

seems the way acpid does it that it ships a SIGTERM, waits a few seconds then SIGKILL

also - this would be for gcloud (kvm) - our current support on aws is using xen which prob. works diff
