### ISSUE TITLE
Panic when attempting to run a PHP app

### ISSUE THREAD

**Issue by teekay** [nanovms/nanos#1090]
I have a midsize PHP app I wanted to test in Nanos, with Ops. I created a config file (see below) and ran it with this result:

```
ops load php_7.2.13 -c nanos.json
[php artisan serve]
2020/03/22 16:14:39 mkfs:parse error unknown property discriminator 91

panic: exit status 1

goroutine 1 [running]:
github.com/nanovms/ops/cmd.loadCommandHandler(0xc00037db80, 0xc0005e8ae0, 0x1, 0x3)
        /Users/eyberg/go/src/github.com/nanovms/ops/cmd/load.go:192 +0x1eca
github.com/spf13/cobra.(*Command).execute(0xc00037db80, 0xc0005e8a50, 0x3, 0x3, 0xc00037db80, 0xc0005e8a50)
        /Users/eyberg/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:830 +0x2ae
github.com/spf13/cobra.(*Command).ExecuteC(0xc000113680, 0x1175fe1, 0xc00043bf88, 0xc0000da058)               /Users/eyberg/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:914 +0x2bb
github.com/spf13/cobra.(*Command).Execute(...)
        /Users/eyberg/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:864
main.main()
        /Users/eyberg/go/src/github.com/nanovms/ops/ops.go:8 +0x28
```

The config looks like this:
``` json
{
  "Args": ["artisan", "serve"],
  "Files": [".env", "artisan", "server.php"],
  "Dirs": ["app", "bootstrap", "config", "database", "node_modules", "public", "resources", "storage", "tests",  "tmp", "vendor"],
  "Env": {
  },
  "RunConfig": {
    "Verbose": true,
    "Accel": false,
    "Memory": "2G",
    "Ports": [8000]
  }
}
```
My environment: Win10 with WSL v2 - I ran the above in a Ubuntu inside WSL.

**Comment by eyberg** [comment]
thank you for filing the issue,

this looks like it's puking on the generated manifest file and very good to confirm that it is on win10 cause i'm willing to bet it is a filename issue, is it possible to see any pwd/tree output to confirm? 

(eg: do any of the paths look like "c:\" ?)

2 other things.

1) getting the manifest would help - ```ops run -m ``` exists but I don't think we have the equivalent for ```ops load``` although if you're comfortable modifying ops a quick cut/paste could get that

2) there's an ops branch that might get you around this issue -> https://github.com/nanovms/ops/tree/quoteManifest

**Comment by eyberg** [comment]
https://github.com/nanovms/ops/issues/475

**Comment by teekay** [comment]
Thank you for your response.

There's no "c:" in my path, in WSL the path looks like `/mnt/c/Users/tomas/...`.

I checked out and built the `quoteManifest` branch of ops and tried again, with a different failing result:

```
/home/tomas/src/ops/ops load php_7.2.13 -c nanos.json
warning: overwriting existing file artisan hostpath old: "artisan" new: artisan
[php artisan serve]
2020/03/23 10:00:18 mkfs:metadata (children:(config:(children:(services.php:() queue.php:() cache.php:() mail.php:() ....
php 2:serve 1:artisan) environment:(USER:root) program:php_7.2.13/php)
log full

panic: exit status 2

goroutine 1 [running]:
github.com/nanovms/ops/cmd.loadCommandHandler(0xc000351900, 0xc0006449f0, 0x1, 0x3)
        /home/tomas/src/ops/cmd/load.go:189 +0x16d5
github.com/spf13/cobra.(*Command).execute(0xc000351900, 0xc000644960, 0x3, 0x3, 0xc000351900, 0xc000644960)
        /home/tomas/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:830 +0x29d
github.com/spf13/cobra.(*Command).ExecuteC(0xc000232a00, 0x0, 0x100380, 0xc00010e058)
        /home/tomas/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:914 +0x2fb
github.com/spf13/cobra.(*Command).Execute(...)
        /home/tomas/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:864
main.main()
        /home/tomas/src/ops/ops.go:8 +0x27
```

(after `mkfs:metadata`, there was a long list of filenames that I truncated here)

Hope this helps.

**Comment by teekay** [comment]
Please note that I'm seeing this 2nd error also when running a large Node.js app.

**Comment by eyberg** [comment]
ah - have you tried doing the nightly release to see if that gets you further along? ```ops load -n``` - this log full msg was fixed a few wks ago but we haven't cut a new release since - specifying '-n' will use the latest nightly build of the kernel

**Comment by teekay** [comment]
That was it, thanks!

**Comment by eyberg** [comment]
we'll keep this tkt open until a) we've cut an official release w/the log full bug and b) the ops branch either gets merged or refactored (it's not merged because I think it needs more work)

**Comment by eyberg** [comment]
log full fix was put into the latest release 0.1.24 - so just waiting on the ops quoteFix branch to get refactored/merged to close this out

**Comment by wjhun** [comment]
Can this be closed, or is it still pending resolution of https://github.com/nanovms/ops/issues/454?

**Comment by francescolavra** [comment]
This can be closed, ops no longer uses the mkfs binary to create images and so doesn't have to create a manifest file anymore.
