### ISSUE TITLE
future work page cache / readv/writev hookup to page-cache

### ISSUE THREAD

**Issue by eyberg** [nanovms/nanos#1115]

**Comment by wjhun** [comment]
#1125

**Comment by wjhun** [comment]
The read side of this is complete, but the write interface to tfs is still linear-only.

The steps I picture are:
- Make an sg write interface for tfs (e.g. filesystem_write_sg). Simple buffer writes can use a "filesystem_write_linear" wrapper which just calls filesystem_write_sg with an sg that contains a single buffer.
- Eliminate the copy in file_write
- Make writev take advantage of zero copy with the new interface, translating the iovec to an sg.
