### ISSUE TITLE
main-loop: WARNING: I/O thread spun for 1000 iterations

### ISSUE THREAD

**Issue by convolvatron** [nanovms/nanos#114]
in the process of playing with the hpet i looked into this further. basically if the interrupt rate exceeds the service rate qemu is going to complain (i.e. set a periodic timer with too high a frequency)

not...sure what to do here. level interrupts on virtio queue?, but thats kind of a pain. 

anyways, opening to track

**Comment by francescolavra** [comment]
Unable to reproduce (tested with `make run TARGET=webg`, with and without KVM acceleration, Qemu version 5.0.50, client-side command `ab -c1000 -n10000 http://127.0.0.1:8080/`).
Closing
