### ISSUE TITLE
filesystem benchmark

### ISSUE THREAD

**Issue by wjhun** [nanovms/nanos#1166]
We should either import or create a little benchmark runtime test to measure file I/O performance so we can keep track of improvements and regressions as we develop tfs.

**Comment by wjhun** [comment]
This was addressed to some degree with the addition of a simple write test in #1191. Will keep this open until we come upon a more comprehensive test, however.

**Comment by uma-sethuraman** [comment]
Hello @wjhun, my team members and I are interested in contributing to this issue. Is there still something we can add to the filesystem benchmark test?

**Comment by wjhun** [comment]
@uma-sethuraman  You are certainly welcome to expand on the crude little test that lives in test/runtime/write.c, but we don't have a specific ask so much. We've mostly used it to compare performance of different drivers and to try and detect (by manual inspection, alas) performance regressions.

A more exhaustive test could certainly be useful, especially if it allows us to compare metrics across platforms. But we haven't enumerated any criteria (@francescolavra - do you have any suggestions here based on what you've found bringing up databases on nanos?), so you would kind of be on your own (or could just generally draw from what other generic fs benchmarks measure - or even just port one, if the license is permissible - e.g. no GPL)...

**Comment by francescolavra** [comment]
I think a useful addition to the tests in test/runtime/write.c would be some code that creates a large number (says, thousands) of files, writes a small amount of data in each file, syncs the filesystem with a call to sync(), then deletes the files and syncs again. This would stress-test many parts of the FS and pagecache code, and provide a workload somewhat similar to that of a database application.

**Comment by uma-sethuraman** [comment]
Thank you @francescolavra @wjhun ! We are interested in this issue and will start working on adding what Francesco mentioned to test/runtime/write.c.
