### ISSUE TITLE
support for device trees

### ISSUE THREAD

**Issue by wjhun** [nanovms/nanos#1221]
It's not clear yet what we'll be using as a bootloader for arm64. If we make use of an existing bootloader, we may need to interpret a device tree blob (dtb) placed by the bootloader at a specific location. If we roll our own, we may need to parse a text device tree file and convert it to a format we can use within the kernel (e.g. add to root tuple).

See: https://www.kernel.org/doc/html/latest/arm64/booting.html
Device tree for RPI 4 (bcm2711): https://github.com/raspberrypi/linux/blob/rpi-4.19.y/arch/arm/boot/dts/bcm2711-rpi-4-b.dts

**Comment by eyberg** [comment]
think this can be closed now? https://github.com/nanovms/nanos/blob/94b9a9e68647cfaf520776edf2e3d3313cb990e7/src/devicetree/devicetree.c
