### ISSUE TITLE
openstack rollup

### ISSUE THREAD

**Issue by eyberg** [nanovms/nanos#1225]
not sure what all is necessary to support - it uses kvm underneath w/virtio-net && virtio-block (and also virtio-rng)

![image](https://user-images.githubusercontent.com/22410/87702765-aa7e4580-c74e-11ea-9445-480f6e2b53b1.png)

however currently it is just rebooting (uploaded as a raw disk - maybe there are different options to specify when provisioning

this was done using devstack under fusion so it could be the nested virt as well - idk

https://docs.openstack.org/devstack/latest/

**Comment by eyberg** [comment]
@mkhon mentioned this is working on buster via vexxhost yet I'm still repro'ing this on ussuri?

```
eyberg@zulu:~$ nova-manage --version
21.1.0
```

```
assertion r != 0 failed in /Users/eyberg/go/src/github.com/nanovms/nanos/src/x86_64/region.h: allocate_region() on line 55; halt
assertion r != 0 failed in /Users/eyberg/go/src/github.com/nanovms/nanos/src/x86_64/region.h: allocate_region() on line 55; halt
assertion r != 0 failed in /Users/eyberg/go/src/github.com/nanovms/nanos/src/x86_64/region.h: allocate_region() on line 55; halt
assertion r != 0 failed in /Users/eyberg/go/src/github.com/nanovms/nanos/src/x86_64/region.h: allocate_region() on line 55; halt
assertion r != 0 failed in /Users/eyberg/go/src/github.com/nanovms/nanos/src/x86_64/region.h: allocate_region() on line 55; halt
asser
```

**Comment by mkhon** [comment]
"allocation_region() on line 55" assertion fails only when running m1.nano (128 MB RAM) flavor.
For other flavors nanovms on zulu enters reboot loop - needs to be investigated further.

**Comment by mkhon** [comment]
Reboot loop can be reproduced by running the following command on zulu:

```
qemu-system-x86_64 -enable-kvm -m 512 -no-shutdown -drive file=/opt/stack/data/nova/instances/37cde04d-a875-4ecb-b1ca-f1ade1e00623/disk2,format=qcow2,if=none,id=drive-virtio-disk0,cache=none -device virtio-blk-pci,scsi=off,bus=pci.0,addr=0x4,drive=drive-virtio-disk0,id=virtio-disk0,bootindex=1 -serial stdio -display none -cpu host
```

This command succeeds on any other Linux host I have access to.
zulu is running inside fusion so I think there is some issue with nested virtualization.

**Comment by mkhon** [comment]
The problem is that "zulu" has too old CPU that does not support XSAVE:

```
eyberg@zulu:~$ ./cpuid -1 | grep -E 'synth|XSAVE'
      (simple synth)  = Intel Core i7-900 (Bloomfield D0) / Xeon Processor 3500 (Bloomfield D0) / Xeon Processor 5500 (Gainestown D0), 45nm
      FXSAVE/FXRSTOR                         = true
      XSAVE/XSTOR states                      = false
      OS-enabled XSAVE/XSTOR                  = false
   (multi-processing synth): multi-core (c=4), hyper-threaded (t=2)
   (APIC widths synth): CORE_width=4 SMT_width=1
   (APIC synth): PKG_ID=0 CORE_ID=3 SMT_ID=0
   (synth) = Intel Xeon Processor 3500 (Bloomfield D0) / Xeon Processor 5500 (Gainestown D0), 45nm
eyberg@zulu:~$ 
```

**Comment by mkhon** [comment]
We don't actually use XSAVE now (use only FXSAVE) so may be we should just stop trying to enable XSAVE during kernel initialization (the VM is killed when we try to set CR4_OSXSAVE (bit 18) in cr4 in init_service()

**Comment by eyberg** [comment]
if this fixes the booting problem can we just optionally enable it? - we ran into something similar with the firecracker issue here, i'm also ok with just saying "your hardware needs to be at least 10 years young." ;) and we can keep a compatiblity list - that's perfectly fine imo

**Comment by mkhon** [comment]
@eyberg we currently don't use it at all (XSAVE) so I think we should just stop trying to enable it. When we get back to XSAVE we should enable it optionally (like Linux does for example) or just fail early with proper error message if XSAVE is not available (this code is actually there but temporarily disabled as we don't use XSAVE)

**Comment by wjhun** [comment]
Removing the enable is fine. See #1081
