### ISSUE TITLE
un-supported version of nasm comment killing nightly mac build

### ISSUE THREAD

**Issue by eyberg** [nanovms/nanos#1227]
https://github.com/nanovms/nanos/blob/master/src/x86_64/crt0.s#L127 - although if you git blame this line is really damn old

https://stackoverflow.com/questions/48148597/can-a-hashtag-be-used-as-a-comment-in-assembly-nasm

this might be correlated w/the fact that the nightly build is taking 27min? to install wget && nasm on mac?

**Comment by eyberg** [comment]
```
In file included from /Users/distiller/project/src/hyperv/include/hyperv_internal.h:7:
/Users/distiller/project/src/hyperv/include/atomic.h:33:11: error: invalid output constraint '=@ccc' in asm
        : "=@ccc" (res),                /* 0 */
          ^
/Users/distiller/project/src/hyperv/include/atomic.h:61:7: error: invalid output constraint '=@ccc' in asm
    : "=@ccc" (res),        /* 0 */
      ^
/Users/distiller/project/src/hyperv/include/atomic.h:119:1: error: invalid output constraint '=@cce' in asm
ATOMIC_CMPSET(32);
^
/Users/distiller/project/src/hyperv/include/atomic.h:111:11: note: expanded from macro 'ATOMIC_CMPSET'
        : "=@cce" (res),                /* 0 */         \
          ^
3 errors generated.
make[1]: *** [/Users/distiller/project/output/stage3/src/hyperv/vmbus/hyperv.o] Error 1
make: *** [stage3] Error 2
```

well now it's failing here as well -> https://app.circleci.com/pipelines/github/nanovms/nanos/441/workflows/cd96f0ed-3f0b-4f96-9680-90fa56d073ba/jobs/4676

**Comment by wjhun** [comment]
The latter build failure is from gcc, not nasm. It's due to use of a newly-added asm constraint in the hyperv atomics, which fails with the old clang in the CI build. Working on a fix.
