### ISSUE TITLE
Support A0 instance types

### ISSUE THREAD

**Issue by eyberg** [nanovms/nanos#1245]
right now we are using A1V2 instance sizes but those are rather beefy - the A0's are still 750mb ram so should be plenty and we should support them

**Comment by eyberg** [comment]
well... i don't see which pricing page is correct https://azure.microsoft.com/en-us/pricing/details/virtual-machines/linux/ or https://azure.microsoft.com/en-us/pricing/details/cloud-services/ 

but it looks like we should be shooting for the B1LS instance types instead - @mkhon - maybe look at that instead of A0

**Comment by eyberg** [comment]
```By the way, B1ls works ok - it is just A0 issue.```

**Comment by mkhon** [comment]
I found out that A2 has the same issue.

The error on both A0 and A2 is:

```
STORVSC: storvsc scsi_status = 2, srb_status = 18
STORVSC: storvsc_inquiry_done: target 0, lun 0, host_status 0, scsi_status 2
SCSI SENSE 00 00 20 ff ff ff ff 00 00 00 00 00 00 00 00 00 00 00: KEY 0, ASC/ASCQ 00/00
STORVSC: max chans 1
[9:51 PM] scsi_status 2 - SCSI_STATUS_CHECK_COND
[9:51 PM] srb_status 18 - SRB_STATUS_DATA_OVERRUN
```
