### ISSUE TITLE
additional esx volumes

### ISSUE THREAD

**Issue by eyberg** [nanovms/nanos#1249]

**Comment by francescolavra** [comment]
Usage notes:
An ESXi disk is created in the same way as a bootable image:
- from a raw volume file `volume.raw` created with the dump tool, create `volume.vmdk` and `volume-flat.vmdk`:
```
qemu-img convert -f raw -O vmdk -o subformat=monolithicFlat volume.raw volume.vmdk
```
- upload the 2 VMDK files created above to the ESXi datastore and make a copy of the "flat" file in the same way as Ops does when creating an ESXi image
- attach an additional disk to an instance (either when creating the instance, or by editing an existing instance) by selecting "Add hard disk" -> "Existing hard disk", then selecting as disk file the volume.vmdk file from the datastore (keep the other options to their default value)
