### ISSUE TITLE
additional aws volumes

### ISSUE THREAD

**Issue by eyberg** [nanovms/nanos#1250]
the real work here is to add xen pv support

**Comment by francescolavra** [comment]
Usage notes:
- upload a raw volume file `volume.raw` (created with the mkfs tool) to an S3 bucket
- create a new AWS snapshot by importing the above file from the S3 bucket, using the AWS CLI tools:
```
aws ec2 import-snapshot --description "myVolume" --disk-container "file://containers.json"
```
Example of containers.json file:
```
{
    "Description": "myVolume",
    "Format": "raw",
    "UserBucket": {
        "S3Bucket": "nanovms-nanos",
        "S3Key": "volume.raw"
    }
}
```
- to check the progress status of a snapshot import operation:
```
aws ec2 describe-import-snapshot-tasks --import-task-ids import-snap-xxxxxxxxxxxxxxxx
```
(where `import-snap-xxxxxxxxxxxxxxxx` is the "ImportTaskId" value from the response to the previous command). When the "Status" value in the response to this command is "completed", the snapshot has been created, and the "SnapshotId" attribute in the response contains the ID of the newly created snapshot
- when creating an AWS instance, add a new volume to the instance, specifying the snapshot ID from above
