### ISSUE TITLE
fix pagecache locking

### ISSUE THREAD

**Issue by wjhun** [nanovms/nanos#1253]
The pagecache was originally written with a spinlock protecting accesses to the page tree (held during traversal of pages - during which pages may be added or removed) and a spinlock protecting state transitions of the pages themselves (including removal from previous state list to new state list). When nodes were added, the pages lock changed to a per-node pages tree lock but with the same semantics.

For operations on a node (file), this model seems simple enough: hold the node's pages lock during the operation (usually a traversal, but could also be walking page tables) and only take the state lock when making state transitions or touching a completions vector. (State transitions as a result of asynchronous I/O completions can occur outside of a node lock being held. Needless to say, no node lock acquisition should be attempted while holding the state lock...)

For performing page evictions across the entire cache, however, the pages lock isn't currently being taken - making evictions unsafe on SMP. This lock acquire can be avoided here by instead moving evicted pages to state PAGECACHE_PAGESTATE_FREE - keeping meta for the evicted page resident and relinquishing memory (really this interface a future free physical page / epoch list #1079).

Incidentally, this change also allows for future optimizations: The freed page metas remain in the pages trees and remain associated with the same virtual address. A "refault" - faulting on a page which was previously evicted - causes a page fill and return to the new list. Refault statistics are kept persistently across eviction / fault cycles, and can be used to improve cache performance by reducing the number of redundant faults for a frequently-used page.

**Comment by sanderssj** [comment]
Closed by #1282
