### ISSUE TITLE
implement frame "pause" method

### ISSUE THREAD

**Issue by wjhun** [nanovms/nanos#1254]
runloop_internal makes a call to thread_pause to take care of time accounting. This kind of violates a tacit understanding that the core parts of the kernel are independent of unix, which is one of what could be multiple syscall interfaces exposed to threads. Consider adding another frame method - like FRAME_PAUSE - for a callback (thunk) from the scheduler, and remove the unix-specific includes and thread_pause from schedule.c.

**Comment by francescolavra** [comment]
Fixed by #1269.
