### ISSUE TITLE
hpet timer error

### ISSUE THREAD

**Issue by jsultond** [nanovms/nanos#1255]
I ran into an issue when I was using the qemu command at https://github.com/nanovms/nanos/wiki/using-the-qemu-remote-gdb-interface on an image generated using OPS. Qemu starts, and I can connect to it using nanos .gdbinit, but continuing results in the below assertion failure. 

ffffffff8000e73a	(runloop_internal + 000000000000020a/0000000000000321)
assertion gsi >= 0 failed in /home/jsultond/Build/nanos/src/x86_64/hpet.c: timer_config() on line 147; halt

qemu version:

QEMU emulator version 4.2.0 (Debian 1:4.2-3ubuntu6.4)
Copyright (c) 2003-2019 Fabrice Bellard and the QEMU Project developers

gcc version:

QEMU emulator version 4.2.0 (Debian 1:4.2-3ubuntu6.4)
Copyright (c) 2003-2019 Fabrice Bellard and the QEMU Project developers

gdb version:

GNU gdb (Ubuntu 9.1-0ubuntu1) 9.1
Copyright (C) 2020 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

**Comment by francescolavra** [comment]
@jsultond the QEMU command line in that Wiki page was outdated, and specifically was missing the `-machine q35` option that is now required by the current Nanos kernel. I updated the Wiki page with a working command line: if you use that, the HPET timer error will go away (tested with QEMU version 5.0.50, but it should work equally fine with QEMU version 4.2.0).
