### ISSUE TITLE
multiple definition of `sockaddr`

### ISSUE THREAD

**Issue by ronaudinho** [nanovms/nanos#1266]
**OS**: Manjaro 20.1
**Kernel**: 5.4.52-1-MANJARO
**GCC**: 10.1.0

i got this error on `make run-noaccel` while trying to build from 0e13e4f
```
ld: nanos/output/platform/pc/src/unix/socket.o:nanos/src/unix/socket.h:4: multiple definition of `sockaddr'; nanos/output/platform/pc/src/net/netsyscall.o:nanos/src/unix/socket.h:4
```

i made local changes on https://github.com/nanovms/nanos/blob/af2b48726915caaa953de3f26e0273bbf7d0fd0c/rules.mk#L66
to `CFLAGS+=    -Wall -Werror -Wno-char-subscripts -Wno-address-of-packed-member -Wno-array-bounds` to get around the following error
```
/nanos/platform/pc/service.c:595:49: error: array subscript 2147483648 is outside array bounds of ‘u8[1]’ {aka ‘unsigned char[1]’} [-Werror=array-bounds]
```
not sure if this is related.

**Comment by francescolavra** [comment]
Thanks for reporting the issue. Both compiler errors will be fixed when #1267 is merged.
