### ISSUE TITLE
accessing current thread in syscall continuations

### ISSUE THREAD

**Issue by wjhun** [nanovms/nanos#1271]
Continuations for syscalls typically enclose the invoking thread, referring to it in place of 'current' (usually, 't'). While the thread pointer is accessible from within the closure body of the continuation, there are other contexts in which it is needed. For example, if a syscall continuation touching some user buffer causes a protection fault, the fault handler will attempt to send a signal to current. If current was not restored before continuation, it will end up delivering the fault to the thread last scheduled to run on the current cpu.

With #1269, an active thread has a pause method invoked to settle up system time accounting. Yet no resumption of accounting occurs on a continuation - only the next return to userspace. It's not clear where such a resume method would be called, since syscall continuations can be served from the scheduling queues just as well as one of the several "completions vector" service routines or some other structure like a vqmsg - there isn't a single point where these continuations (which could be thunks, status_handlers ... anything) are dispatched that can also be used to restore current and apply a resume method.

A brute force approach is to just manually restore current to the enclosed thread at the head of each continuation _within unix_. There could still be an issue if some syscall - e.g. sendfile - leads to a chain of asynchronous operations outside the scope of unix, where no thread context is being maintained. A fault on a user buffer anywhere in that sequence could not be reliably associated with the offending thread, for another thread may have been scheduled between a request and a completion.

Another idea is to enqueue each completion as two words -  together as a completion type, perhaps, which includes the completion as well as a thread address (or invalid). (The lock free queue is currently only word-sized elements, but variants with a size parameter can be added.) Since completions go into a variety of containers - queue, vector, vqmsq, etc. - the extra housekeeping can be done by helpers: save saves current into the thread field and calls its pause method. Restore restores current from the thread field and calls its resume method.

#1254, #1269

**Comment by francescolavra** [comment]
The idea to enqueue each completion as two words - which include a thread address - doesn't seem feasible, because tasks are generally enqueued by storage or network drivers, which are not aware of which thread (if any) will end up processing the data; for example, network drivers enqueue a task whenever network packets are received, but it's impossible to know which thread(s) will handle the packets until the socket read routine is called; for storage drivers, a task being enqueued to handle responses to I/O requests can handle multiple responses, which could be processed by different threads, so it's impractical to specify a target thread when a task is being enqueued.
#1297 tackles this issue by assigning the duty to set the current context to all asynchronous handlers that touch user buffers.

**Comment by francescolavra** [comment]
I realize the original comment about using a multi-word queue perhaps wasn't referring to the scheduler bhqueue or runqueue, but to the pagacache completion_vecs. This would indeed  solve the issue for storage I/O, but not for network packets.
In #1297, access to user buffers in the pagecache code is handled by retrieving the current thread in pagecache_write_sg(), and restoring the thread in pagecache_write_sg_finish().

**Comment by wjhun** [comment]
> The idea to enqueue each completion as two words - which include a thread address - doesn't seem feasible, because tasks are generally enqueued by storage or network drivers, which are not aware of which thread (if any) will end up processing the data

Thread context does not need to be restored at such a low level unless something within a driver / lwIP / DMA would directly access a user buffer. Syscalls are suspended at a higher layer - usually in the blockq (which is an ideal place to restore the thread anyway as it is already recorded along with the continuation in a blockq_item). Since blocking on sockets are all interruptible blocks handled by blockq (unless I'm missing something?), ci->thread restoration can simply be handled in blockq_apply_bi_locked.

The idea above wasn't to necessarily restore the thread from the scheduler, but rather at any point downstream where a syscall continuation would be invoked. The continuation itself is opaque and specific to the thread that is blocking, so I didn't see any problem with packing the thread pointer and restoring that before applying the continuation. But somehow that seems kind of inelegant to me now, and doing it in the blockq would seem to cover the vast majority of instances of blocking syscalls anyway.

A possible issue here would be if a user buffer were accessed by lwIP code _directly_ as a result of a received packet or timer expiry, or if a user buffer was used for dma / zero copy. A fault on a bad address in such a case might not be associated with the faulting thread. I don't think (?) there are cases of this currently, and we currently call tcp_write with TCP_WRITE_FLAG_COPY (and socket_write_udp creates a pbuf and copies without any explicit block). But in any future case where this isn't true, it would seem only reasonable that the top portion of the syscall should validate (by walking the page tables, not with the range check validate we currently use) the user memory before initiating the request anyway, obviating the need to handle a recoverable fault in a continuation.

The other case involves uninterruptible blocks, which for the most part are filesystem operations. But I think your changes that address this in the pagecache may suffice for this case, provided that accesses to user buffers are isolated to the pagecache. (However I think the read side needs to be covered as well, as the read completion will write into user buffers.)

Between restoring the thread before invoking blockq actions and touching user buffers in the pagecache, I think most if not all of the cases would be covered. Again, user buffer validation will be needed for any future zero-copy / DMA directly out of user buffers, but I think this would be the case regardless.

**Comment by francescolavra** [comment]
> A possible issue here would be if a user buffer were accessed by lwIP code _directly_ as a result of a received packet or timer expiry, or if a user buffer was used for dma / zero copy. A fault on a bad address in such a case might not be associated with the faulting thread. I don't think (?) there are cases of this currently

Right, as far as I can see, currently lwIP touches only kernel-allocated buffers, in both the transmit and receive paths.
