### ISSUE TITLE
local hyper-v reboot loop

### ISSUE THREAD

**Issue by eyberg** [nanovms/nanos#1275]
tried running an image that works on azure, but sits in a reboot loop on local hyper-v (win10) - not sure if it should be in a diff. format (this was booted as gen1)

**Comment by eyberg** [comment]
![b](https://user-images.githubusercontent.com/22410/92527722-52a70c80-f1dc-11ea-8e15-2d1328c48205.png)

**Comment by mkhon** [comment]
This is fixed in #1270
