### ISSUE TITLE
Encounter an error when running a Golang application with ops

### ISSUE THREAD

**Issue by QiZhang1997** [nanovms/nanos#1276]
I am a beginner in unikernel. Recently when I tried to run a blockchain application with **ops**, I encountered the following error.
```
booting /home/qi/.ops/images/bdledger.img ...
assigned: 10.0.2.15
exec: "getent": executable file not found in $PATH
exit status 3
```
What should I do to solve this problem? Do I need to package the **getent** executable file under linux into unikernel? Thanks very much!

**Comment by eyberg** [comment]
@QiZhang1997 we don't have support for running other executables from inside these applications and don't plan on adding support either - are you the author of that code? if so, https://golang.org/pkg/os/user/ might provide native support for accessing what you are looking for, if it's open source I can point you at other resources as well

**Comment by QiZhang1997** [comment]
OK! Thanks for your help.
