### ISSUE TITLE
CNCF-Runtime discussion/presentation(?)

### ISSUE THREAD

**Issue by raravena80** [nanovms/nanos#1280]
Hello Nano team,

I'm one of the co-chairs of the CNCF SIG-Runtime. I believe the nanos project falls within the scope of the SIG. It would be great for your team to present at our meeting.

Let me know if this something you'd be interested in. If yes, please feel free to add it to our [agenda](https://bit.ly/cncf-sig-runtime-meeting-notes) or reach out to me (raravena80 at gmail.com)

Thanks!

**Comment by eyberg** [comment]
following up via email
