### ISSUE TITLE
ci fail from ops https://github.com/nanovms/ops/issues/613

### ISSUE THREAD

**Issue by eyberg** [nanovms/nanos#1290]
https://app.circleci.com/pipelines/github/nanovms/nanos/662/workflows/1fa9873a-76a6-4a86-8969-68e1cc0834ae/jobs/4960

**Comment by eyberg** [comment]
https://github.com/nanovms/ops/pull/614

**Comment by francescolavra** [comment]
With https://github.com/nanovms/ops/pull/617, the "You have disabled hardware acceleration" warnings when running the Go tests go away.

**Comment by eyberg** [comment]
i rebuilt last night && tests pass so closing
