### ISSUE TITLE
time test failure

### ISSUE THREAD

**Issue by wjhun** [nanovms/nanos#1305]
This failure has been occurring intermittently in CI (e.g. https://app.circleci.com/pipelines/github/nanovms/nanos/727/workflows/fb206d54-7f70-46d4-86e2-d5dc9d235b53/jobs/5043)

```
test_posix_timers: signal test passed
test_itimers: testing itimer interface
test_itimers: starting itimer test
test_itimers: starting: which 0, interval 1000 nsec, one-shot
test_itimers: test passed; delta 245111 nsec
test_itimers: starting: which 0, interval 1000 nsec, periodic
test_itimers: test passed; delta 49470 nsec
test_itimers: starting: which 0, interval 1000000 nsec, one-shot
test_itimers: test passed; delta 197433 nsec
test_itimers: starting: which 0, interval 1000000 nsec, periodic
test_itimers: test passed; delta 83756 nsec
test_itimers: starting: which 0, interval 1000000000 nsec, one-shot
test_itimers: test passed; delta 3553654 nsec
test_itimers: starting: which 0, interval 1000000000 nsec, periodic
test_itimers: test passed; delta 2854846 nsec
test_itimers: starting: which 0, interval 2000000000 nsec, one-shot
test_itimers: test passed; delta 5243714 nsec
test_itimers: starting: which 0, interval 2000000000 nsec, periodic
test_itimers: test passed; delta 23520440 nsec
test_itimers: itimer test passed
test_cputime: test_cputime: proc_delta 281541: thread_delta 630392
make[3]: *** [Makefile:375: run-noaccel] Error 1
make[3]: Leaving directory '/home/circleci/project/platform/pc'
make[2]: *** [Makefile:92: run-noaccel] Error 2
make[2]: Leaving directory '/home/circleci/project'
make[1]: *** [Makefile:83: runtime-tests-noaccel] Error 2
make[1]: Leaving directory '/home/circleci/project'
make: *** [Makefile:76: test-noaccel] Error 2
```

The check "proc_delta < thread_delta" fails because the accounted process time is less than the accounted thread time. This may be related to recent changes involving thread pause/resume (at which points some per-thread time bookkeeping occurs).

**Comment by francescolavra** [comment]
I can't rule out possible issues in time bookkeeping in the kernel, but the test itself is a bit flawed, because the reference for the thread time (thread_ts) is retrieved before the reference for the process time (proc_ts), and the inevitable delay between these two retrievals means that the two references don't refer to the exact same timestamp, so the delta calculations in the following loop may be skewed, and this could cause the test to fail.

**Comment by wjhun** [comment]
> the inevitable delay between these two retrievals means that the two references don't refer to the exact same timestamp, so the delta calculations in the following loop may be skewed, and this could cause the test to fail.

Right. I think the check should be comparing the absolute timestamps and not the deltas.
