### ISSUE TITLE
add futex runtime test

### ISSUE THREAD

**Issue by wjhun** [nanovms/nanos#1306]
We don't currently have an explicit test for futexes. We could use an exhaustive test that stresses both the futex interface as well as correctness on single and multiple-core instances. The test should run under both a Linux host and nanos as a parity check.

**Comment by uma-sethuraman** [comment]
Hello, my team members and I are students at the University of Texas at Austin. We are interested in contributing to Nanos as a part of a project for our virtualization class. Could we take on this issue?

**Comment by wjhun** [comment]
> Hello, my team members and I are students at the University of Texas at Austin. We are interested in contributing to Nanos as a part of a project for our virtualization class. Could we take on this issue?

Sure. I have just assigned it to you. Thanks!

**Comment by wjhun** [comment]
Note that the Linux Test Project has several futex tests. They rely on fork() to run, and thus won't work on nanos without modification. (Also note that simply changing "forks_child" in the tst_test structs won't work, either.) You could see whether it is possible to modify these tests to use pthreads instead of spawning child processes.

Please note, however, that LTP is GPL code - and thus we cannot import any of it into the nanos tree. While still need a futex runtime test of our own for catching regressions, adapting LTP for a single run of tests may help isolate futex bugs in the near term, which would still be very helpful.

See https://github.com/nanovms/nanos/wiki/Running-tests-from-Linux-Test-Project

**Comment by uma-sethuraman** [comment]
Hello @wjhun, I have started working on this issue and familiarizing myself with how the futex tests work in the Linux Test Project. I was wondering if you could give me some more guidance about how I can adapt the LTP futex tests for nanos and what your expectations are.
