### ISSUE TITLE
interface for per-cpu init callbacks and resource allocation

### ISSUE THREAD

**Issue by wjhun** [nanovms/nanos#1328]
We have various areas around the kernel that want some state stored in the per-cpu info. We could use some interface for registering per-cpu initialization callbacks to be invoked when CPUs come online.

One thing to take into consideration when coming up with such an interface is that we may eventually want the ability to bring cores on and offline. There isn't a pressing need to implement this now, but it would be nice if interfaces started supporting it. (So, for instance, per-cpu init functions should not assume that they are only being called during kernel init...)

**Comment by wjhun** [comment]
Could be useful for multiple io queue support in #1316

**Comment by wjhun** [comment]
Expanding this issue to cover per-cpu resource allocation: Presently, resources for MAX_CPUS cores are allocated in init_cpuinfos(), a broadcast ICR_TYPE_STARTUP ipi is sent to all MPs, and we just see what comes back (and hope there aren't more than MAX_CPUS cores). It would be better to just do this dynamically for each CPU probed (via ACPI / MP tables, or on vcpu hotplug notification) and remove the artificial MAX_CPUS limit.

**Comment by francescolavra** [comment]
With #1540, per-CPU resources are allocated dynamically and the MAX_CPUS limit is removed.
