### ISSUE TITLE
fix 64kB stage2 size limit

### ISSUE THREAD

**Issue by wjhun** [nanovms/nanos#1336]
The stage2 disk image must remain under 64kB to allow loading it in a single bios int 13H call from within stage1. While we don't want stage2 to get any larger, this can be a show stopper when stage2 code compiled with debug code or lower optimization causes this boundary to be exceeded.

Investigate improving the stage1 bootloader to make multiple bios calls to fulfill the stage2 read if needed.

**Comment by estherlyoon** [comment]
My team members and I can start investigating this

**Comment by wjhun** [comment]
> My team members and I can start investigating this

Ok! Have a look at platform/pc/boot/stage1.s. You'll see the int 13h call to read stage2. Try to inflate the size of stage2 to exceed 64kB (disabling the size check in mkfs) and see if you can trigger a failure in stage1. Then perhaps change stage1 to do a loop of read calls and see if that fixes the issue.

**Comment by francescolavra** [comment]
Closed via https://github.com/nanovms/nanos/pull/1342.
