### ISSUE TITLE
Network problem in p2p communication

### ISSUE THREAD

**Issue by QiZhang1997** [nanovms/nanos#1354]
Recently, I'm going to run a P2P chat application with nanos. [(here)](https://github.com/libp2p/go-libp2p-examples/tree/master/chat). However, I have met some problems. I tried to locate the bug. But I didn't find a way to debug golang multithreaded programs in nanos, so I didn't get anything. The problem is as follows:

Here I run this application on my Linux host. The correct output is as follows:
```
qi@qi-HP-Pavilion-Notebook:~/go-libp2p-examples/chat$ ./chat -sp 3001
/ip4/0.0.0.0/tcp/3001
Run './chat -d /ip4/127.0.0.1/tcp/3001/p2p/QmZCPxsEJq18tPESVL6JYFXWnu2BDXceaRLTsw35QoTgtB' on another console.
You can replace 127.0.0.1 with public IP as well.

Waiting for incoming connection

This node's multiaddresses:
 - /ip4/127.0.0.1/tcp/3001
 - /ip4/192.168.8.138/tcp/3001
 - /ip4/10.0.85.1/tcp/3001
 - /ip4/192.168.122.1/tcp/3001
 - /ip4/172.17.0.1/tcp/3001
 - /ip4/172.18.0.1/tcp/3001
```
I can connect this node in another terminal by running `./chat -d /ip4/127.0.0.1/tcp/3001/p2p/QmZCPxsEJq18tPESVL6JYFXWnu2BDXceaRLTsw35QoTgtB`

The above results are obtained by running the application directly on the Linux host. After that, I run this application with nanos. I got the following output:
```
qi@qi-HP-Pavilion-Notebook:~/go-libp2p-examples/chat$ ops run -c config1.json -p 3001 chat
 You are running an older version of Ops. 
 Update: Run  `ops update`
[./chat -sp 3001]
booting /home/qi/.ops/images/chat.img ...
assigned: 10.0.2.15
/ip4/0.0.0.0/tcp/3001
Run './chat -d /ip4/127.0.0.1/tcp/3001/p2p/QmPn5jpY3Xf5USG8H5ZjVW9Q8TtGfR9VYvWL6yQzQE1bkS' on another console.
You can replace 127.0.0.1 with public IP as well.

Waiting for incoming connection

This node's multiaddresses:
```
I can't connect this node by running `./chat -d /ip4/127.0.0.1/tcp/3001/p2p/QmPn5jpY3Xf5USG8H5ZjVW9Q8TtGfR9VYvWL6yQzQE1bkS` on another console. You can notice that the output is also different from previous one. This node's multiaddress is null. But it doesn't even report an error, just the output is different. I don't know where the problem is. Maybe it's my network configuration problem? Or nanos does not support building P2P networks? Or is it because some goroutines are used in the program that makes it unable to run normally?

I don't know if anyone has encountered similar problems. I hope you can help me. Thanks very much.

**Comment by eyberg** [comment]
this seems to get an EOF and then panics when running the first node - it seems to be failing here ->

```
ops run --trace -p 3001 -p 49153 -c config.json chat &>/tmp/o
```

when creating this socket ->

```
1 sleep interruptible (on "futex")
            4 run thread, cpu 0, frame 0xffff800002602c00, rip 0x46e083, rsp 0x1315ffd88, rdi 0x148038d48, rax 0x1, rflags 0x286, cs 0x2b, sysret
            4 socket
            4 direct return: -97, rsp 0x1484e6530
```

```
            4 run thread, cpu 0, frame 0xffff800002602c00, rip 0x46d9dd, rsp 0x1315ffdb8, rdi 0x1315ffdb8, rax 0x0, rflags 0x202, cs 0x2b, sysret
            4 write
panic:             4 direct return: 7, rsp 0x1315ffd68
    2 run thread, cpu 0, frame 0xffff800002601c00, rip 0x46d9dd, rsp 0x1a89ffdc0, rdi 0x1a89ffdc0, rax 0x0, rflags 0x202, cs 0x2b, sysret
    2 epoll_pwait
    2 direct return: 0, rsp 0x1a89ff780
            4 run thread, cpu 0, frame 0xffff800002602c00, rip 0x46d935, rsp 0x1315ffd68, rdi 0x2, rax 0x7, rflags 0x246, cs 0x2b, sysret
            4 write
EOF            4 direct return: 3, rsp 0x1315ffcd8
```

we can look into this but just as a fyi - this particular example application is built to be interactive and takes stdin and that's not something we'd ever support

**Comment by QiZhang1997** [comment]
> this seems to get an EOF and then panics when running the first node - it seems to be failing here ->
> 
> ```
> ops run --trace -p 3001 -p 49153 -c config.json chat &>/tmp/o
> ```
> 
> when creating this socket ->
> 
> ```
> 1 sleep interruptible (on "futex")
>             4 run thread, cpu 0, frame 0xffff800002602c00, rip 0x46e083, rsp 0x1315ffd88, rdi 0x148038d48, rax 0x1, rflags 0x286, cs 0x2b, sysret
>             4 socket
>             4 direct return: -97, rsp 0x1484e6530
> ```
> 
> ```
>             4 run thread, cpu 0, frame 0xffff800002602c00, rip 0x46d9dd, rsp 0x1315ffdb8, rdi 0x1315ffdb8, rax 0x0, rflags 0x202, cs 0x2b, sysret
>             4 write
> panic:             4 direct return: 7, rsp 0x1315ffd68
>     2 run thread, cpu 0, frame 0xffff800002601c00, rip 0x46d9dd, rsp 0x1a89ffdc0, rdi 0x1a89ffdc0, rax 0x0, rflags 0x202, cs 0x2b, sysret
>     2 epoll_pwait
>     2 direct return: 0, rsp 0x1a89ff780
>             4 run thread, cpu 0, frame 0xffff800002602c00, rip 0x46d935, rsp 0x1315ffd68, rdi 0x2, rax 0x7, rflags 0x246, cs 0x2b, sysret
>             4 write
> EOF            4 direct return: 3, rsp 0x1315ffcd8
> ```
> 
> we can look into this but just as a fyi - this particular example application is built to be interactive and takes stdin and that's not something we'd ever support

OK, thanks a lot! I noticed that there was no /dev/stdin device in nanos. It may be the real cause of the program crash.

**Comment by QiZhang1997** [comment]
@eyberg Hello! I tested another example in this repository that does not require stdin. [here](https://github.com/libp2p/go-libp2p-examples/tree/master/echo). I run this program in one terminal using `./echo -l 1000`. In another terminal, I run this program with nanos.
```
qi@qi-HP-Pavilion-Notebook:~/go-libp2p-examples/echo$ ops run -c config2.json -p 10001 echo
 You are running an older version of Ops. 
 Update: Run  `ops update`
[./echo -l 10001 -d /ip4/127.0.0.1/tcp/10000/p2p/QmNxm1JrhLAuNva2Wxmdzuqccu89xKVBunKwWHLbhkBhvN]
booting /home/qi/.ops/images/echo.img ...
assigned: 10.0.2.15
panic: runtime error: index out of range [0] with length 0

goroutine 1 [running]:
main.makeBasicHost(0x2711, 0x1b8020000, 0x0, 0x4, 0x0, 0x0, 0x1b812f1f0)
	/home/qi/go-libp2p-examples/echo/main.go:67 +0x83f
main.main()
	/home/qi/go-libp2p-examples/echo/main.go:98 +0x213
exit status 5
```
Because `basicHost.Addrs()` returns nothing in nanos. The program crashed. So I comment out lines 67 to 75. Now it looks like this. 
```
	//addr := basicHost.Addrs()[0]
	//fullAddr := addr.Encapsulate(hostAddr)
	log.Println(hostAddr)
	log.Printf("I am %s\n", basicHost.ID())
	/*if insecure {
		log.Printf("Now run \"./echo -l %d -d %s -insecure\" on a different terminal\n", listenPort+1, fullAddr)
	} else {
		log.Printf("Now run \"./echo -l %d -d %s\" on a different terminal\n", listenPort+1, fullAddr)
	}*/
```
I tested it again.
```
qi@qi-HP-Pavilion-Notebook:~/go-libp2p-examples/echo$ ops run -c config2.json -p 10001 echo 
 You are running an older version of Ops. 
 Update: Run  `ops update`
[./echo -l 10001 -d /ip4/127.0.0.1/tcp/10000/p2p/QmQchudynm4NDGoFAFsSFDJSoF2mfq31rXYdfRwbv3XSss]
booting /home/qi/.ops/images/echo.img ...
assigned: 10.0.2.15
2020/12/10 08:28:54 /p2p/QmYsa1j4oyecdmPEtpBKCG1AVA69BvUMaDxRCmnJdWbftA
2020/12/10 08:28:54 I am QmYsa1j4oyecdmPEtpBKCG1AVA69BvUMaDxRCmnJdWbftA
2020/12/10 08:28:54 opening stream
08:28:54.744  INFO     swarm2: got error on dial: dial tcp4 127.0.0.1:10000: connect: connection reset by peer swarm_dial.go:420
2020/12/10 08:28:54 failed to dial : all dials failed
  * [/ip4/127.0.0.1/tcp/10000] dial tcp4 127.0.0.1:10000: connect: connection reset by peer
exit status 3
```
There is no further error message. What I am curious about is that `basicHost.Addrs()` should be able to display the ip address of the node after I port mapping the virtual machine, but it does not actually. It seems that the nanos network is not connected to the outside world

**Comment by francescolavra** [comment]
The most likely reason why `basicHost.Addrs()` returns an empty list is that the kernel doesn't support Netlink sockets (#453).

**Comment by QiZhang1997** [comment]
@francescolavra OK! I got it. Thanks a lot!

**Comment by francescolavra** [comment]
Netlink sockets are now supported (see https://github.com/nanovms/nanos/pull/1407) in the Nanos master branch, and I verified that both applications mentioned in this issue are now able to retrieve the list of IP addresses. @QiZhang1997 please note that in order to the echo application to listen on the correct network interface when running on Nanos, you have to replace the loopback address at https://github.com/libp2p/go-libp2p-examples/blob/master/echo/main.go#L47 with the IP address assigned to the "real" network interface, i.e. 10.0.2.15 with the typical network setup (but the application run on the host should still use 127.0.0.1 if it wants to communicate with the Nanos instance).

**Comment by francescolavra** [comment]
This issue has been resolved since the addition of netlink socket support, closing.
