### ISSUE TITLE
virtual box support

### ISSUE THREAD

**Issue by eyberg** [nanovms/nanos#1400]
from https://github.com/nanovms/ops/issues/888 we currently don't have virtual box support - i know vbox used to provide their own tap kernel extension which would be nice to have on mac os, although I don't know what the status is for that on big sur, also - vbox can be managed headlessly ala vagrant

regardless I think we are missing at least one driver

**Comment by francescolavra** [comment]
With https://github.com/nanovms/nanos/pull/1422, the kernel runs also with the default paravirtualization interface, and it's no longer necessary to select KVM as paravirtualization interface.
