### ISSUE TITLE
update .circleci arm release

### ISSUE THREAD

**Issue by eyberg** [nanovms/nanos#1420]
aarch64 build has diff naming/path that we should update .circle builds with

```
cp output/platform/virt/bin/kernel.elf ~/.ops/0.1.31/kernel.img
cp output/platform/virt/boot-stub.img ~/.ops/0.1.31/boot.img
```

**Comment by wjhun** [comment]
With #1430, the path for the kernel image has been reverted to output/platform/virt/bin/kernel.img.

**Comment by francescolavra** [comment]
#1772 added ARM support to the release script.
#1858 updated the build-virt CircleCI job to publish ARM build artifacts that can be retrieved by Ops via the `--nanos-version` option.
