### ISSUE TITLE
Potential error(e.g., deadlock) due to the unreleased lock &mut

### ISSUE THREAD

**Issue by jenny-cheung** [nanovms/nanos#1539]
Dear developers:
         First, thank you for your checking. In the function, worker, the lock &mut may not be correctly released if the `val==BADLUCK` satisfies. The fix is to insert pthread_mutex_unlock(&mut) before returning` NULL`.

https://github.com/nanovms/nanos/blob/1e91c71cf71799b093286750dbc29ab5deea19c5/test/runtime/futexrobust.c#L41

```
void *
worker(void *v)
{
    ...;
    for (;;) {
        usleep(rand_r(&seed) % 1000);
        acquire_mutex(&mut);
        usleep(rand_r(&seed) % 1000);
        if (val == BADLUCK) {  // the condition may happen
            val++;
            printf("worker %p aborting after %d increments\n", self, myincs);
            return NULL; //  the lock &mut may be not be released correctly
        }
       ...;
}
```

Best,

**Comment by francescolavra** [comment]
Hi @jenny-cheung, the worker function doesn't release the mutex on purpose when `val==BADLUCK`: this is a test to check that other threads are able to make a robust mutex consistent after a thread terminates while holding the mutex. So this is not a bug.

**Comment by jenny-cheung** [comment]
@francescolavra  Okay, thank you for your reply.
