### ISSUE TITLE
Panic while loading pkg locally

### ISSUE THREAD

**Issue by rrs45** [nanovms/nanos#1550]
Not sure why its panic'ing

`$ ops pkg load -l rasa_actions_2.7.1 -c /mnt/disks/disk1/nanos/rasa_actions_config.json -n --show-debug
panic: interface conversion: interface {} is []interface {}, not map[string]interface {}

goroutine 1 [running]:
github.com/nanovms/ops/fs.(*tfs).encodeMetadata(0xc0017a9dc0, 0xc0005158e0, 0x8, 0x1d535a0, 0xc0004c6618)
	/Users/eyberg/go/src/github.com/nanovms/ops/fs/tfs.go:144 +0x3f9
github.com/nanovms/ops/fs.(*tfs).encodeTuple(0xc0017a9dc0, 0xc00018a780)
	/Users/eyberg/go/src/github.com/nanovms/ops/fs/tfs.go:165 +0xf5
github.com/nanovms/ops/fs.(*tfs).encodeMetadata(0xc0017a9dc0, 0xc0005158f0, 0xa, 0x1f51900, 0xc00018a780)
	/Users/eyberg/go/src/github.com/nanovms/ops/fs/tfs.go:144 +0x298
github.com/nanovms/ops/fs.tfsWrite(0xc00000edc0, 0xc0de00, 0x0, 0x0, 0x0, 0xc000501da0, 0xc0017a9d50, 0x0, 0x0)
	/Users/eyberg/go/src/github.com/nanovms/ops/fs/tfs.go:373 +0x273
github.com/nanovms/ops/fs.(*MkfsCommand).Execute(0xc000c5d3c8, 0x0, 0x0)
	/Users/eyberg/go/src/github.com/nanovms/ops/fs/mkfs.go:269 +0x28f
github.com/nanovms/ops/lepton.createImageFile(0xc0009fb4a0, 0xc000501e30, 0x0, 0x0)
	/Users/eyberg/go/src/github.com/nanovms/ops/lepton/image.go:414 +0x1d0
github.com/nanovms/ops/lepton.BuildImageFromPackage(0xc0001de240, 0x37, 0xc0001e2800, 0x5, 0x8, 0xc0005158ce, 0x2, 0xc0001cac00, 0x26, 0xc0001cafc0, ...)
	/Users/eyberg/go/src/github.com/nanovms/ops/lepton/package.go:348 +0xbe
github.com/nanovms/ops/cmd.loadCommandHandler(0xc0002c7400, 0xc000188840, 0x1, 0x6)
	/Users/eyberg/go/src/github.com/nanovms/ops/cmd/cmd_pkg.go:289 +0x4a5
github.com/spf13/cobra.(*Command).execute(0xc0002c7400, 0xc000188780, 0x6, 0x6, 0xc0002c7400, 0xc000188780)
	/Users/eyberg/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:830 +0x2c2
github.com/spf13/cobra.(*Command).ExecuteC(0xc00024f900, 0x0, 0x1d8b120, 0xc00008c058)
	/Users/eyberg/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:914 +0x30b
github.com/spf13/cobra.(*Command).Execute(...)
	/Users/eyberg/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:864
main.main()
	/Users/eyberg/go/src/github.com/nanovms/ops/ops.go:8 +0x2a`

**Comment by francescolavra** [comment]
This is an issue in ops, not in Nanos. It has been fixed in https://github.com/nanovms/ops/pull/1090, which has been merged after the latest ops release, so to get the fix you would have to either build ops from source, or wait for a new release.

**Comment by rrs45** [comment]
Is there a way to downgrade Ops to previous versions?

**Comment by eyberg** [comment]
fyi, a new release was cut just now https://github.com/nanovms/ops/releases/tag/0.1.25 , older releases have tarballs here: https://github.com/nanovms/ops/releases

however, we're now storing old versioned binary releases like we do with nanos as well and we'll be creating a directory of them on ops.city in the near future
