### ISSUE TITLE
VMWare Workstation Support?

### ISSUE THREAD

**Issue by Vadoola** [nanovms/nanos#1583]
I was wondering if there was any plans to support VMWare Workstation, or if any one has any guidance on how to get it working?

I'm toying with the idea of using nanos for things, but it's very early stages. For work we use VMWare Workstation on Windows for many tasks already and I thought it would be nice to create some tests nanos images and run them on Workstation.

I'm building my executable and images on a Arch Linux VM and so far I have tried two separate tactics with different results.

1. Build a virtualbox image, export the appliance as an OVA and import that into VMWare. I've had no real luck with this. Farthest I got was manually creating a VM with the vmdk inside the OVA and booting it, but all I get is a blank screen, doesn't actually seem to boot.
2. Second attempt create a raw .img file. Then I used qemu-img convert to change it to vmdk, and created a new VM in Workstation with it. This actually seemed to kind of work. It boots and shows some text from my executable. However my test executable is a Rust application with a simple Actix-web server. It gives the error "NET: no network interface found". I've tried using a bridged, NAT, Host only network adapter and none of them seem to work.

I realize this VMWare Workstation isn't currenlty supported, but I was wondering if anyone could offer advice on how to get this working, or if anyone had any knowledge on if official Workstation support was planned?

**Comment by eyberg** [comment]
both vsphere and fusion should work (ops has deploy capability to vsphere) so I'm not quite sure what you'd be running into but we can take a look

**Comment by Vadoola** [comment]
I was aware of the VSphere support with ops. I haven't spent as much time on it but didn't get it working either. I only have access to ESXi (free version) which doesn't support Resource Pools.

I was unaware that Fusion was supported, as I haven't seen any documentation on that but I might have missed it.

It could be something I'm simply overlooking since I'm pretty new to nanos. If there is any sort of log files you would like me to supply, or further details I may have left outlet me know.

**Comment by sanderssj** [comment]
Hi @Vadoola,
Your instinct to make the img file and convert it to vmdk was right, that's the way to do it. The problem with the missing network device is that nanos supports only PV device drivers such as vmxnet3, but the Workstation seems to want to use an e1000 NIC without giving you an option to change it in the UI. I was able to get networking working in nanos with Workstation Player 16 by modifying the vmx file to change "e1000" to "vmxnet3" as mentioned [here](https://communities.vmware.com/t5/VMware-Workstation-Pro/Configure-vNIC-to-use-vmxnet3-driver/td-p/1371374). If you can generate your own vmx file to go with the vmdk, you should be able to have a vm that will work properly with Workstation.

I hope that helps--let me know if you have any other problems running it with Workstation.

**Comment by Vadoola** [comment]
That seems to have worked perfectly in my testing so far. It even worked to upload it to an ESXi (Free version) hypervisor, which I hadn't managed to get working yet since the free version doesn't support resource pools.

It would be nice if the process was a bit smoother. While running nanos images in Workstation is great for testing for my purposes, I'm not sure if there is much demand. I'm fine with this issue being closed, and thank you for the help.

Below are some more detailed steps on what I did and how I got it working for anyone else wanting this info. I'm not saying this is the most ideal way to do it, just what I've tried and had succeed so far, there could be a smoother way.

1. Create a raw disk image following the instructions in the [Bare Metal guide for ops](https://nanovms.gitbook.io/ops/bare_metal). I've tested a few options including using DHCP and a static IP and they seem to work fine. I also did my testing with VMWare Workstation 15, and ESXi 6.7
2. Convert the raw image created by ops using qemu-img convert. The command I used was `qemu-img convert -f raw -O vmdk old.img new.vmdk`
3. In VMWare Workstation Create a new VM, by going to File-> New Virtual Machine
4. In the popup window Click "Custom (advanced)" before clicking "Next"
5. Select your hardware compatibility. If you plan on running it on Workstation, you can leave it set to the default. For me that was Workstation 15.X. If you plan on uploading it to ESXi select an ESXi version from the dropdown (this can be changed at a later point) and click "Next"
6. On the next page select "I will install the operating system later" and click "Next"
7. On the next screen it asks what the Guest operating system is. I selected Other, and Other. It's possible there are other combinations, like Linux that might work fine here...I'm not knowledgeable enough about nanos or the inner workings of VMWare currently to know what the ideal selection here should be.
8. Continue through the next several screens selecting the options that are most appropriate for your nanos image, name, cores, ram, etc.) until you get to the "Select a Disk" screen. 
9. Select the option for "Use an existing disk", click next, and browse to find the vmdk you created using qemu-img convert. When you click "Next" you may get asked if you want "Convert existing virtual disk to newer format" In my testing so far, you have to select "Convert" in order for it to work properly, but I have not dug to deep to see if you could keep the format and still have it working.
10. After it converts click finish, before running the VM, open up the VMs ".vmx" file Look for a line starting with `ethernet0.virtualDev` and make sure it is set to = "vmxnet3". It's possible this line won't exist and needs to be added (as was the case in my testing)
11. Boot your nanos vm and it should work.

I was also able to get this same VM running on the free version of ESXi, by using the below steps.
1. Power off the VM if it's already running.
2. If you had previously set the Hardware Compatibility to Workstation, change it now. Click VM->Manage->Change Hardware Compatibility, and change it to an ESXi compatibility level.
3. Click VM->Manage->Upload and select the ESXi server to upload it to.

You could probably also create the VM on ESXi free using the VMDK similar to how I did it in Workstation, but I have not tested this.

**Comment by eyberg** [comment]
i added your notes to https://github.com/nanovms/ops-documentation/pull/259 && opened https://github.com/nanovms/ops/issues/1163 to explore tighter integration to workstation - looks like there is an API available

I'm willing to bet the resource pools aren't necessary for ESX integration (although they are required for ops today as evidenced by the documentation - https://nanovms.gitbook.io/ops/vsphere )
