### ISSUE TITLE
Arm support in FAQ

### ISSUE THREAD

**Issue by jserv** [nanovms/nanos#1607]
Current [FAQ](https://github.com/nanovms/nanos/blob/master/FAQ.md) stated:
> Q: Do you support ARM?
> A: Not today although it's not out of the question for the future.

However, Nanos deploys not only to x86 hardware but also Arm64. Should FAQ document be revised?

**Comment by eyberg** [comment]
yes, the docs need updating - we can deploy to the rpi4 today

**Comment by eyberg** [comment]
updated https://github.com/nanovms/nanos/blob/master/FAQ.md
