### ISSUE TITLE
Discord chat server

### ISSUE THREAD

**Issue by naturallymitchell** [nanovms/nanos#1622]
Could you please make a place for multichannel, live chatting about nanos? (preferably with audio and video, ie Discord)

**Comment by eyberg** [comment]
At this time the company doesn't really have the resources to administer this themselves but anyone that is interested is more than welcome to form their own channel or other forum/platform. Additionally, I think the magnitude of what we are working on has the potential to foster many different communities/user groups - not just having one official chat room.
