### ISSUE TITLE
network question

### ISSUE THREAD

**Issue by sash2222** [nanovms/nanos#1632]
Hi. I have rather a question of understanding architecture.
I understand that the kernel provides execution of only one process (binary, etc.). But is there a way to extend the network. I'm talking about a mesh network service. Basically, this is some kind of proxy (envoy), which is controlled by an external level (consul, istio). Can KLIBS help in this? This would allow isolated secure networks to be created from applications.
Of course, you can manage networks at the level of a cloud provider, but then the network cannot be expanded outside the provider, project, etc.
Perhaps I misunderstood something in the concept and, for example, can I build an application with envoy support and manage it through the consul?

**Comment by eyberg** [comment]
envoy was designed to deal with container networking issues, many of which aren't really applicable to how unikernels are deployed; keep in mind containers generally rely on an additional layer of underlay/overlay networks which is one of the main reasons why this type of software exists to begin; having said that it is conceivable that you could make an envoy-compatible client that plugs in as a klib but it would require some discussion on what you are precisely wanting to achieve and should weigh those objectives against perhaps other lesser effort designs

**Comment by eyberg** [comment]
just as an addendum at least on GCP and AWS there is the concept of a 'shared vpc' https://cloud.google.com/vpc/docs/shared-vpc  && https://docs.aws.amazon.com/vpc/latest/userguide/vpc-sharing.html
