### ISSUE TITLE
Support multiple Nameserver IPs

### ISSUE THREAD

**Issue by jasonrichardsmith** [nanovms/nanos#1656]
Single IP nameservers restricts us to one point of failure across availability zones.

This NLB sits in front of a consul cluster for DNS.

https://codeberg.org/jasonrichardsmith/google-cloud-ms-demo-on-nanovms/src/branch/master/templates/consul/nlb.j2#L43-L48

If one AZ goes down the consul cluster can recover but if the IP I set for the nameserver is in that AZ... DNS is down until I rebuild the images.

**Comment by eyberg** [comment]
you can always create your own /etc/resolv.conf and include that file in your image

I think what you're asking for is possibly to change ops' config option, 'NameServer' to include multiple nameservers? we could do that

**Comment by jasonrichardsmith** [comment]
yes the NameServers option.

**Comment by eyberg** [comment]
https://github.com/nanovms/ops/pull/1246
