### ISSUE TITLE
Net console does not seem to be dialing out to netconsole_ip

### ISSUE THREAD

**Issue by jasonrichardsmith** [nanovms/nanos#1667]
I have setup fluentbit with a static IP at 192.168.1.100 in a VPC with the following configuration
```
[INPUT]
    Name        tcp
    Listen      0.0.0.0
    Port        5170
    Format      none


[OUTPUT]
    Name cloudwatch
    Match   *
    region eu-west-1
    log_group_name fluent-bit-cloudwatch
    log_stream_prefix from-fluent-bit-
    auto_create_group true
```

I have setup machines with 
```
{
  "ManifestPassthrough": {
	  "consoles": ["+net"],
	  "netconsole_ip" :"192.168.1.100",
	  "netconsole_port": "5170"
  }
}
```
No logs reach fluentbit.

On regular linux machine I can run the following:
```
echo "test" | nc 192.168.1.100 5170
```
And the logs arrive at fluentbit. Same security groups, etc.

**Comment by sanderssj** [comment]
The netconsole uses UDP over IP for transport, so you need to listen for UDP instead of TCP (and test with nc -u).

**Comment by jasonrichardsmith** [comment]
OK, I will try that.

**Comment by jasonrichardsmith** [comment]
I was able to get it working like that. Thank you.
