### ISSUE TITLE
Simple http request with Rust failing (Reqwest/Ureq)

### ISSUE THREAD

**Issue by Hraesvel** [nanovms/nanos#1668]
Hey there, I've been playing around with Nanos and have been able to run a server build with Actix. However, my server needs to make HTTP requests to an external API.

I'm able to ping my server and make requests to it. Albeit the returned JSON is invalid since it can't fetch the data it needs from the external API.

So i did some testing on a more basic test app to see if it was Request/Hyper also tried another crate ureq and also have test async and blocking versions. 

My logs have been returning an error like this.

```
thread 'main' panicked at 'fail: reqwest::Error { kind: Request, url: Url { scheme: "https", cannot_be_a_base: false, username: "", password: None, host: Some(Domain("some_api.com")), port: None, path: "/", query: None, fragment: None }, source: hyper::Error(Connect, ConnectError("dns error", Os { code: 16, kind: ResourceBusy, message: "Device or resource busy" })) }', src/bin/request_a.rs:6:47
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

```rust
// example of basic app
use reqwest::get;
use tokio;

#[tokio::main]
async fn main() {
    let yt = get("https://some_api.com").await.expect("failed to run GET request");
    if yt.status().is_success() {
        println!("Success");
    }
}
```

Both have this line in their error message `Os { code: 16, kind: ResourceBusy, message: "Device or resource busy" })) }',`  and based on hyper's error message is caused by trying to access the DNS.

I just started to use Nanos, so is this an issue or a security thing that i need to configure.

**Comment by eyberg** [comment]
you're running into a dns issue probably because of missing libs

there are quite a few different ways to skin this cat in rust (espc by setting different runtimes/options for dependencies in Cargo.toml) but taking your example and what I found at 

https://github.com/seanmonstar/reqwest

```
eyberg@box:~/zzzz/ur$ cat src/main.rs
// example of basic app
use reqwest::get;
use tokio;

#[tokio::main]
async fn main() {
    let yt = get("https://nanos.org")
        .await
        .expect("failed to run GET request");
    if yt.status().is_success() {
        println!("Success");
    }

    println!("Hello, world!");
}

eyberg@box:~/zzzz/ur$ cat Cargo.toml
[package]
name = "ur"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = { version = "0.11", features = ["json"] }
tokio = { version = "1", features = ["full"] }

eyberg@box:~/zzzz/ur$ ops run target/debug/ur
 You are running an older version of Ops.
 Update: Run  `ops update`
booting /home/eyberg/.ops/images/ur.img ...
en1: assigned 10.0.2.15
Success
Hello, world!
```

i was able to run this w/ops w/normal 'cargo build'

what you can try are 2 other ways:

1) you can try with musl as it'll auto-include dns for you:

```
cargo build --target x86_64-unknown-linux-musl
```

but there are tradeoffs for that

2) you'd need to dive into this with ```ops run --trace my_program``` but if you do that (and I would redirect that output cause it'll be substantial eg: ```ops run --trace my_program &>/tmp/out``` i'm willing to bet you'll find lines like this ->

```
1 openat
1 "/lib/x86_64-linux-gnu/libnss_compat.so.2" - not found
1 direct return: -2, rsp 0x7fc5b388
1 run thread, cpu 0, frame 0xffffc00001400800, pc 0x476579a1dcdd, sp 0x7fc5b388, rv 0xfffffffffffffffe
1 openat
```

which means you'll probably need to add the libraries that it is using for dns:

```
mkdir -p etc lib/x86_64-linux-gnu
cp /lib/x86_64-linux-gnu/libnss_compat.so.2 lib/x86_64-linux-gnu/.
cp /lib/x86_64-linux-gnu/libnss_files.so.2 lib/x86_64-linux-gnu/.
cp /lib/x86_64-linux-gnu/libresolv.so.2 lib/x86_64-linux-gnu/.
cp /etc/nsswitch.conf etc/.

eyberg@box:~/zzzz/ur$ tree etc lib
etc
└── nsswitch.conf
lib
└── x86_64-linux-gnu
    ├── libnss_compat.so.2
    ├── libnss_files.so.2
    └── libresolv.so.2

1 directory, 4 files
```

then put in your config.json:

```
{
  "Dirs": ["lib", "etc"]
}
```

also - there are some more examples here:
https://github.com/nanovms/ops-examples/tree/master/rust/01-hello-world

**Comment by Hraesvel** [comment]
Cheers went with option 2.

**Comment by eyberg** [comment]
cool if this works for you we'll go ahead and close and if you think there needs to be more docs or something on the ops-examples repo happy to add anything there
