### ISSUE TITLE
clone3 system call missing

### ISSUE THREAD

**Issue by richiejp** [nanovms/nanos#1735]
I'm trying to use nodejs17/18 and the binaries from OpenSUSE and NixOS use versions of glibc which use clone3. From the POV of Nanos there is little difference between clone and clone3.

I have tried implementing clone3 and it seems to work: https://github.com/nanovms/nanos/commit/df1a78ed16f90c644970f2ab82b955732a8098fb

It definitely needs some cleanup before being submitted however.

**Comment by francescolavra** [comment]
Thanks for the patch, it looks good to me. If you clean it up (mainly de-duplicate code with the existing clone syscall, e.g. create a new clone_internal() function which will contain the code starting from the handling of CLONE_THREAD, and also fix indentation issues by using 4-space indents) and submit it as a pull request, we can review and merge it.

**Comment by richiejp** [comment]
I finally got chance to try cleaning it up:  #1750

**Comment by richiejp** [comment]
Strangely I can't recreate the original issue now; it seems to fallback to clone just fine. I did recreate the ops images, so perhaps this flushed something out, or there was a glibc/pthread update in the meantime. This issue would also effect containers if clone3 has been disallowed by seccomp for e.g.
