### ISSUE TITLE
Question: Does nanos have DNS caching?

### ISSUE THREAD

**Issue by zeroecco** [nanovms/nanos#1780]
Today in one of my production workflows an external DNS provider `8.8.8.8` was temporarily unavailable to my unikernels. This lead to immediate failure of the onboard application.

My question: Does nanos have a DNS cache of some kind on board? And if no, is there a flag to enable it? If no, can I ask for this as a feature?

**Comment by eyberg** [comment]
by default linux doesn't cache w/out installing something else locally and we emulate that behavior; having said that - the underlying network stack lwip *does* have a dns cache although i'm unsure of the particulars; i know @francescolavra was just looking at this for a few other things though https://github.com/nanovms/nanos/pull/1779 && https://github.com/nanovms/nanos/pull/1778 so he might have something to add here

we probably would want to keep the same behavior as found on linux (eg: no caching by default) (but would be open to adding some sort of flag for caching behavior) - i guess my question though is how this translates to the original problem - how would you handle this normally on linux? if you can't access the dns server ip then the dns record for it wouldn't much matter? i'd imagine you would need/want some sort of retry logic regardless if it was nanos || linux; if we can suss that out a bit more it'd help figure out what we might want to do here

**Comment by zeroecco** [comment]
What you say makes a lot of sense. In this case, for whatever reason `8.8.8.8` was the only thing not responding to 
 requests. 

Normally, in Linux I will have the local dns cache with a TTL in place to serve from even if the DNS provider is unavailable.

We would also have multiple DNS servers (which might already be possible in nanos and falls on me for not thinking of it) in place to fall back to in the case of a resolver mis behaving for any amount of time.

I see #1779 is looking at honoring cache TTLs, but if the DNS cache was serving up the cached stale record to the process I don't _think_ I would have seen the system fall over, but I could be wrong of course.

**Comment by eyberg** [comment]
you can definitely put in multiple dns servers https://docs.ops.city/ops/configuration#nameservers - but again these are not cached themselves - any call to gethostbyname or whatever ends up calling that should not be cached as of right now - you can verify this via

```sudo tcpdump udp port 53```

and a sample program such as this ->

```
package main

import (
	"fmt"
	"net"
	"time"
)

func main() {

	for i := 0; i < 5; i++ {

		addrs, err := net.LookupHost("asdf.com")
		if err != nil {
			fmt.Println(err)
		}

		fmt.Printf("%+v\n", addrs)

		time.Sleep(3 * time.Second)
	}
}
```

as you can see there is no caching

optional caching is something we could look into enabling but if there was a network failure to google's dns server (as ip) it seems like that might be the issue you are running into and we would want to repro what you are seeing there if possible

**Comment by francescolavra** [comment]
DNS handling by our underlying network stack lwIP (which is what #1778 and #1779 are about) is only relevant for hostname resolution done from within the kernel or a klib (such as cloud_init), and does not apply to DNS requests made by the user application, which are entirely dependent on the application itself and/or the system libraries and their configuration.
In general, from your application's perspective, you should expect DNS to work on Nanos in the same way as it would work on Linux when using the same set of system libraries (e.g. /usr/lib/x86_64-linux-gnu/libresolv.so) and configuration files (e.g. /etc/resolv.conf).
So if the unavailability of the DNS provider 8.8.8.8 caused a failure of your application, I think it would have caused the same failure had your application been running under an "equivalent" Linux OS.
By the way, the ["NameServers" configuration option](https://docs.ops.city/ops/configuration#nameservers) in Ops works by creating behind the scenes an /etc/resolv.conf file that is put in the unikernel image.

**Comment by zeroecco** [comment]
I understand! Thank you for answering this question :)
