### ISSUE TITLE
wireguard-go: getsockopt: operation not supported

### ISSUE THREAD

**Issue by rinor** [nanovms/nanos#1795]
inspired by https://nanovms.com/dev/tutorials/running-nanos-wireguard-vpn-gateway, I'm trying to boot [wireguard-go](https://github.com/rinor/wireguard-go) instead of `boringtun`.

- `config.json`
```json
{
  "Args": [
    "-f",
    "wg2"
  ],
  "Env": {
    "LOG_LEVEL": "verbose",
    "WG_PROCESS_FOREGROUND": "1"
  },
  "RunConfig": {
    "Klibs": [
      "tun"
    ],
    "UDPPorts": [
      "51820"
    ]
  },
  "Boot": "nanos/output/platform/pc/boot/boot.img",
  "Kernel": "nanos/output/platform/pc/bin/kernel.img",
  "ManifestPassthrough": {
    "tun": {
      "wg": {
        "ipaddress": "10.0.0.1",
        "netmask": "255.255.255.0",
        "up": "true"
      }
    }
  }
}
```
- `ops run wireguard-go -c config.json`
```sh
booting /home/nanos/.ops/images/wireguard-go-nanos ...
en1: assigned 10.0.2.15
wg2: assigned 10.0.0.1
DEBUG: (wg2) 2022/12/30 12:49:11 Starting wireguard-go version 0.0.20220316-10-g63607f0
DEBUG: (wg2) 2022/12/30 12:49:11 Device started
ERROR: (wg2) 2022/12/30 12:49:11 Failed to listen on uapi socket: file file+net unix:/var/run/wireguard/wg2.sock->: getsockopt: operation not supported
exit status 3
```

- `ops run wireguard-go -c config.json --trace` [trace_nanos_0.1.43.txt](https://github.com/nanovms/nanos/files/10324793/trace_nanos_0.1.43.txt)
```sh
...
netsock_getsockopt error: getsockopt unimplemented optname: fd 12, level 1, optname 38
...
```
Assumed that `optname 38` was about `SO_PROTOCOL` and tried to play with that, but keep hitting https://github.com/nanovms/nanos/blob/3d23ebe02abe4927485d1a6215946f8354195a81/src/net/netsyscall.c#L2314-L2317

Any help/guidance to debug it further is highly appreciated.

**Comment by sanderssj** [comment]
Hi @rinor,
The unix socket being created at /var/run/wireguard/wg2.sock is used for configuring wireguard from another process on the same machine, which won't be possible with a unikernel. In the vpn gateway article we modified boringtun to take a config file instead of needing the unix socket for configuration. Have you modified wireguard-go to be configured in another way?

I'm also looking at the SO_PROTOCOL sockopt to see what it would take to support that.

**Comment by rinor** [comment]
@sanderssj I’m working with a patched wireguard-go version to provide the same https://github.com/WireGuard/wireguard-go/compare/master...rinor:wireguard-go:nanos

**Comment by sanderssj** [comment]
@rinor I've created a branch unixsock-getsockopt that adds in the missing syscall support and it lets wireguard-go startup normally for me now. Give it a try. You can easily do this with your ops command by specifying the commit-id like so:
`ops run wireguard-go -c config.json --nanos-version 336d557`

Let me know if that gets your version working. Thanks!

**Comment by rinor** [comment]
@sanderssj thank you. That branch fixes the mentioned issue in this ticket.

The service is `not fully operational yet` (even though no visible errors/failures on nanos kernel side). I’ll debug further, since now I’m stuck on reading from the socket (timeouts) and will try to check/understand what’s happening there when applying the config.

Nevertheless feel free to close the ticket ince the pr lands on main, unless you prefer to keep this open to track until we make wireguard-go work.

Thanks again and happy new year

**Comment by rinor** [comment]
It turns out that `wireguard-go`, when run on nanos, **can't update the bind port** (triggered when issuing `listen_port=51820` command) causing issues/timeouts when applying the config. 

As a workaround patched `wireguard-go` to start listening by default on port `51820` and skip/ignore `listen_port` command.

So with
- nanos - https://github.com/nanovms/nanos/commit/336d5579a12a872e1309e38b41cc5860dbcd1794
- wireguard-go minimal patch - https://github.com/rinor/wireguard-go/commit/de6469757dbbb320f70186fe0c572fc3fd9dec9b.patch

we have a working version also for `wireguard-go` as we do for `boringtun`.

**Comment by sanderssj** [comment]
https://github.com/nanovms/nanos/pull/1796

**Comment by sanderssj** [comment]
Hi @rinor,
I also fixed the last issue you reported -- the wireguard-go program was hanging when switching ports because a
listening thread wasn't being woken when the old port was closed. This should allow your wireguard-go branch to
work properly without the early assigned port modification.

Thanks for testing this configuration out!

**Comment by rinor** [comment]
Thank you @sanderssj, will test again and report back

**Comment by rinor** [comment]
@sanderssj it works perfectly. Thank you.
