### ISSUE TITLE
Question(klib): firewall - lwip based

### ISSUE THREAD

**Issue by rinor** [nanovms/nanos#1798]
Is there a `firewall` klib planned?
Atm I guess one can use lwip input hooks, but it’s a bit annoying.

Thank you.

**Comment by eyberg** [comment]
in the past we've told users to lean on the various cloud providers networking capabilities as that usually suffices but yes we've looked at creating a simple klib that does a drop pkts on tcp/udp based on ip or network class in a config - would something like that be applicable?

**Comment by rinor** [comment]
> in the past we've told users to lean on the various cloud providers networking capabilities as that usually suffices

And that's perfectly fine and makes sense. For exposed ports that provide services meant to be consumed publicly it's not a big deal, however where _paranoia_ kicks in is related to cases when some of the exposed ports provide services meant to be consumed internally (from a controlled environment/acl) and having that extra `firewall` (understandable that we accept the performance hit) gives and extra protection in cases when cloud network acl/firewalls may not be properly configured.

> but yes we've looked at creating a simple klib that does a drop pkts on tcp/udp based on ip or network class in a config - would something like that be applicable?

A simple klib is be fine and that would serve as a template/starting point for anyone having extra/advanced requirements.

Thank you.
