### ISSUE TITLE
Question(klib): cloud_init - simple auth support

### ISSUE THREAD

**Issue by rinor** [nanovms/nanos#1806]
Assuming that the resources being consumed by `cloud_init` are "protected" with some simple auth schemes, like Basic or token Bearer one, would smth like this be useful, or not that much.
```json
  "ManifestPassthrough": {
    "cloud_init": {
      "download": [
        {
          "src": "https://httpbin.org/hidden-basic-auth/user/passwd",
          "dest": "/test.txt",
          "overwrite": "t",
          "auth": "Basic dXNlcjpwYXNzd2Q=",
        }
      ]
    }
  }
```

or
```json
  "ManifestPassthrough": {
    "cloud_init": {
      "download": [
        {
          "src": "https://httpbin.org/bearer",
          "dest": "/test.txt",
          "overwrite": "t",
          "auth": "Bearer xyztoken"
        }
      ]
    }
  },
  ```
  testing https://github.com/nanovms/nanos/compare/master...rinor:nanos:klib-cloud_init-auth for what I need, just trying to get a feeling if acceptable to push it upstream.

**Comment by eyberg** [comment]
i think we'd be quite ok with adding an optional auth attribute here for that
