### ISSUE TITLE
Add support for LD_LIBRARY_PATH for intrep

### ISSUE THREAD

**Issue by am11** [nanovms/nanos#1810]
`ops` now recognizes the `LD_LIBRARY_PATH` env variable in config: https://github.com/nanovms/ops/commit/a535c7864cc574da0dad9eca4b6b617ea0ab11b9

Similar to regular libs, ops also allow resolving interpreter path in one of the paths pointed by `LD_LIBRARY_PATH` https://github.com/nanovms/ops/commit/8e0f29f8f959f0899897cafe8ddb7d392a0a276f

However, nanos ignores `LD_LIBRARY_PATH`; when I launch nanos with interp at non-standard location and `LD_LIBRARY_PATH` set, it halts from https://github.com/nanovms/nanos/blob/c90e9ebd4743e4e13ce4408291623685910bf9a0/src/unix/exec.c#L251-L253

```sh
booting /Users/am11/.ops/images/myApp ...
en1: assigned 10.0.2.15
couldn't find program interpreter /lib64/ld-linux-x86-64.so.2
```

**Comment by francescolavra** [comment]
As mentioned in https://github.com/nanovms/nanos/pull/1812#issuecomment-1401727139, implementing this feature would make Nanos behave in a non-standard way when locating the ELF interpreter file, and at this point there doesn't seem to be a compelling use case to justify that. Closing
