### ISSUE TITLE
feat(klib - cloud_init): HTTP -> Environment (setenv)

### ISSUE THREAD

**Issue by rinor** [nanovms/nanos#1813]
It would be useful to have the possibility to get and inject environment variables from `cloud_init` download functionality, in addition to file download capability, ex:

- **config.json**
```json
  "ManifestPassthrough": {
    "cloud_init": {
      "download_env": [
        {
          "src": "https://config.provisioner/env01",
          "auth": "Basic dXNlcjpwYXNzd2Q="
        }
      ],
      "download": [
        {
          "src": "https://config.provisioner/e.cfg",
          "dest": "/file.cfg",
          "overwrite": "t",
          "auth": "Basic dXNlcjpwYXNzd2Q="
        }
      ]
    }
  }
```
---

- **https://config.provisioner/env01** **output** can be whatever is easier/faster to implement, ex (just one format can be supported, not all of them, and can deviate from the std shell usage if needed to make the implementation easier):
```ini
VAR_NAME_01="value 01"
VAR_NAME_02="value_02"
VAR_NAME_03=123
```
or
```json
{
  "VAR_NAME_01": "value 01",
  "VAR_NAME_02": "value_02",
  "VAR_NAME_03": 123
}

```

or specific env section (for more advanced usage in the future)
```json
{
  "Env": {
    "VAR_NAME_01": "value 01",
    "VAR_NAME_02": "value_02",
    "VAR_NAME_03": 123
  }
}
```
---

- **expected** actions/results
  - `cloud_init` issues http request to `download_env.src`
  - response content is processed/parsed and if correct env(s) are injected, but response content is not saved to any file, but zeroed
  - injected env(s) are available to `program`
---

- case scenario where such feature is nice to have
  - application uses encrypted config/files from the provisioner (cloud_init file(s) download) and applications requires the password/key/.... to be present on an `env` var upon boot. Since password/key/... (not necessarily the config/file(s) content) is generated and rotated upon each init request  (when the image boots), we can't set it in advance through the static env config during image creation.

**Comment by francescolavra** [comment]
@rinor we are working on this feature. Stay tuned!

**Comment by francescolavra** [comment]
#1822 implements support for populating environment variables retrieved from an HTTP(S) server using JSON syntax.
Example Ops configuration to populate the environment when the server response follows the format below:
```
{
  "VAR_NAME_01": "value 01",
  "VAR_NAME_02": "value_02",
  "VAR_NAME_03": 123
}
```
```
{
  "ManifestPassthrough": {
    "cloud_init": {
      "download_env": [
        {"src": "https://config.provisioner/env01"}
      ]
    }
  }
}
```

Example Ops configuration to populate the environment when the server response follows the format below:
```
{
  "Env": {
    "VAR_NAME_01": "value 01",
    "VAR_NAME_02": "value_02",
    "VAR_NAME_03": 123
  }
}
```
```
{
  "ManifestPassthrough": {
    "cloud_init": {
      "download_env": [
        {"src": "https://config.provisioner/env01", "path": "Env"}
      ]
    }
  }
}
```

This feature can be used with any provisioning server that uses JSON syntax in its response. For example, it can be used to retrieve secrets from a Hashicorp Vault (https://www.vaultproject.io) server, as in the following examples:
- to retrieve a secret at the path `hello` with the KV v2 secrets engine (enabled at the path `/secret`):
```
{"src": "http://10.0.2.2:8200/v1/secret/data/hello", "auth": "Bearer hvs.bgDp7I0ADt6xsy2UYmc08JeE", "path": "data/data"}
```
- to retrieve a secret at the path `my-secret` with the KV v1 secrets engine (enabled at the path `/kv`):
```
{"src": "http://10.0.2.2:8200/v1/kv/my-secret", "auth": "Bearer hvs.bgDp7I0ADt6xsy2UYmc08JeE", "path": "data"}
```
- to retrieve a secret at the path `h` with the Cubbyhole secrets engine (enabled at the path `/cubbyhole`):
```
{"src": "http://10.0.2.2:8200/v1/cubbyhole/h", "auth": "Bearer hvs.bgDp7I0ADt6xsy2UYmc08JeE", "path": "data"}
```
