### ISSUE TITLE
Feature request: shutdown event hook/notification

### ISSUE THREAD

**Issue by nielsbergsma** [nanovms/nanos#1877]
Dear NanoVM-team,

As prior mentioned in https://github.com/nanovms/nanos/issues/1874#issuecomment-1594567807

It would be useful to have some kind of mechanism that signals the program that the VM is terminating and gives it certain amount of time to gracefully shut down. In my case, I using a RocksDB storage engine, and I'm not 100% sure that flushing only the disk will persist all the changes correctly and does not corrupt the state on the attached volume.

**Comment by sanderssj** [comment]
https://github.com/nanovms/nanos/pull/1880 implements sending the user program a SIGTERM signal.
Your program must contain a SIGTERM signal handler that would perform any shutdown operations
before calling exit to signal shutdown is complete. A program without this signal handler will just behave
as before.
