### ISSUE TITLE
vdso calls appear to be unused when running -noaccel

### ISSUE THREAD

**Issue by wjhun** [nanovms/nanos#1888]
This issue was discovered while investigating #1884 as well as attempting to run runtime-tests with acceleration. A call to vdso clock_gettime() would reveal a flaw in the time test, while tests running without acceleration (including CI tests) would mask the issue. This suggests that there may be an issue with our vdso implementation that prevents glibc from selecting vdso calls when running under TCG emulation, causing clock_gettime(2) and other glibc calls to fall back to invoking syscall implementations.

**Comment by francescolavra** [comment]
This is a known issue (#1045) and applies to the time(), clock_gettime() and gettimeofday() vdso calls, which fall back to using their respective syscalls if a pvclock is not available (the vdso_get_now_fn() function returns vdso_now_none unless the registered clock source is VDSO_CLOCK_PVCLOCK).

**Comment by wjhun** [comment]
Ok, makes sense. Closing.
