### ISSUE TITLE
feat(storage): prevent nanos from starting the program if the expected volumes are not available

### ISSUE THREAD

**Issue by rinor** [nanovms/nanos#1927]
The reason of the failure is not important in this context, the source disk may not be attached, the disk name/label is too long or wrongly named/configured on manifest, .... and a **configurable setting** to prevent nanos from starting the program would be very helpful. I would argue that this should be the default behavior and the config used to relax it, but either way is fine.

**Comment by eyberg** [comment]
it's a supported use-case to have the mount points defined but the volume not attached - we support hot-plugging volumes locally and on gcp and aws, having said that we could possibly look at having a config flag to not start something if a volume is not present

**Comment by rinor** [comment]
After #1935 this is not very important.
