### ISSUE TITLE
Scheduled Task Stops Prematurely in Java in Firecracker MicroVM

### ISSUE THREAD

**Issue by Roopsai507** [nanovms/nanos#2025]
I have a Java program that schedules a periodic task to run every 10 seconds using a ScheduledExecutorService. When I run the program locally using ops deploy, it works fine, and the task executes as expected, printing a message every 10 seconds.

However, when I start the same program in a Firecracker MicroVM, the scheduler stops after executing the task only 5 to 6 times.

Code Snippet : 
```import java.util.concurrent.Executors;
import java.util.concurrent.ScheduledExecutorService;
import java.util.concurrent.TimeUnit;

public class PeriodicTaskExample {
    public static void main(String[] args) {
        ScheduledExecutorService executorService = Executors.newScheduledThreadPool(1);
        // Schedule the task to run every 10 seconds
        executorService.scheduleAtFixedRate(() -> {
            try {
                System.out.println("Periodic task executed");
            } catch (Exception e) {
                e.printStackTrace();
            }
        }, 0, 10, TimeUnit.SECONDS);

        // Keeping the main thread alive indefinitely
        try {
            Thread.sleep(Long.MAX_VALUE);
        } catch (InterruptedException e) {
            e.printStackTrace();
        }
    }
}
```
Firecracker Version : 1.6.0
Ops Kernel image : d9743ea
Java Package : java_1.8.0_191

**Comment by eyberg** [comment]
i looked into this briefly using slightly diff. more-up-to-date versions and wasn't reproducing

I tried w/ Firecracker v1.7.0 &&  eyberg/java:20.0.1 on nanos nightly

can you try w/that and see if you're still seeing what you see?

**Comment by Roopsai507** [comment]
Have tried with Firecracker v1.7.0 && eyberg/java:20.0.1 
Ops Kernel image : d9743ea

Still i am facing the same issue.

**Comment by eyberg** [comment]
can you paste a log of '--trace' running here - perhaps we might see what you are hitting?

also since you state that it works fine w/qemu/ops can you show us

```
cat /proc/cpuinfo  | grep model.name
cat /etc/lsb-release
uname -a
```

firecracker by default has a lot of capabilities toggled by default, idk what you might be hitting there but that might be something to look at

also - can you tell us where you are running this? in the cloud? locally? inside of another vm?
