### ISSUE TITLE
At [2.000818] en1: assigned FE80:: 5054: FF: FE12:3456, this step got stuck

### ISSUE THREAD

**Issue by ge1mina023** [nanovms/nanos#2082]
I followed the README.md steps on my M1 chip MacBook Pro for testing. When I entered make run, I got stuck at [2.000818] en1: assigned FE80:: 5054: FF: FE12:3456. After that, there was no response. Did I make a mistake?

process：
`(base) yue@wangyues-MBP nanos % brew update && brew install go wget ent qemu aarch64-elf-binutils

==> Updating Homebrew...
Already up-to-date.
Warning: go 1.23.3 is already installed and up-to-date.
To reinstall 1.23.3, run:
  brew reinstall go
Warning: wget 1.25.0 is already installed and up-to-date.
To reinstall 1.25.0, run:
  brew reinstall wget
Warning: ent 1.0 is already installed and up-to-date.
To reinstall 1.0, run:
  brew reinstall ent
Warning: qemu 9.1.2 is already installed and up-to-date.
To reinstall 9.1.2, run:
  brew reinstall qemu
Warning: aarch64-elf-binutils 2.43.1 is already installed and up-to-date.
To reinstall 2.43.1, run:
  brew reinstall aarch64-elf-binutils
(base) yue@wangyues-MBP nanos % brew tap nanovms/homebrew-toolchains
(base) yue@wangyues-MBP nanos % brew install aarch64-linux-binutils
Warning: nanovms/toolchains/aarch64-linux-binutils 2.41 is already installed and up-to-date.
To reinstall 2.41, run:
  brew reinstall aarch64-linux-binutils
(base) yue@wangyues-MBP nanos % mkdir target-root && cd target-root && wget
https://storage.googleapis.com/testmisc/arm64-target-root-new.tar.gz && tar xzf arm64-target-root-new.tar.gz
(base) yue@wangyues-MBP nanos % make run
make[1]: Nothing to be done for `contgen'.
LD      /Users/yue/code/nanos/output/platform/virt/bin/kernel.elf
MV      kernel.dis kernel.dis.old
STRIP   /Users/yue/code/nanos/output/platform/virt/bin/kernel.img
LD      /Users/yue/code/nanos/output/platform/virt/bin/kernel.elf
MV      kernel.dis kernel.dis.old
make[2]: Nothing to be done for `webg'.
MKFS    image
UUID: 10fd5dd2-130d-3e78-0b26-436b5f5a8faa
metadata
(children:(kernel:()))
UUID: 09013ee3-d7d4-2697-a493-3b70be97bc05
metadata
(arguments:[webg
            longargument]
 children:(etc:(children:(ld.so.cache:()
                          resolv.conf:()))
           lib:(children:(aarch64-linux-gnu:(children:(libc.so.6:()
                                                       libpthread.so.0:()
                                                       libresolv.so.2:()))
                          ld-linux-aarch64.so.1:()))
           webg:())
 debug_exit:t
 environment:(PWD:password
              USER:bobby)
 program:/webg)
qemu-system-aarch64 -machine virt -machine gic-version=2 -machine highmem=off -m 1G  -kernel /Users/yue/code/nanos/output/platform/virt/bin/kernel.img -display none  -device virtio-rng-pci -serial stdio -drive if=none,id=hd0,format=raw,file=/Users/yue/code/nanos/output/image/disk.raw -device virtio-blk-pci,drive=hd0 -no-reboot -semihosting  -device virtio-net,netdev=n0 -netdev user,id=n0,hostfwd=tcp::8080-:8080,hostfwd=tcp::9090-:9090,hostfwd=udp::5309-:5309 -object filter-dump,id=filter0,netdev=n0,file=/tmp/nanos.pcap -accel hvf -cpu host
[0.002590] en1: assigned 10.0.2.15
[2.000680] en1: assigned FE80::5054:FF:FE12:3456
`

**Comment by eyberg** [comment]
this looks fine to me - are you expecting something different?

this looks like you have successfully booted the webg example server though, listening on port 8080

unless you're developing on nanos itself we'd recommend just using ops - https://ops.city

**Comment by ge1mina023** [comment]
> this looks fine to me - are you expecting something different?
> 
> this looks like you have successfully booted the webg example server though, listening on port 8080
> 
> unless you're developing on nanos itself we'd recommend just using ops - https://ops.city

Is this state normal? Or should there be something else appearing.

**Comment by eyberg** [comment]
yes, you are running a test here - this isn't how a normal user would interact with nanos - if you're trying to run a program of your own I'd suggest using ops

**Comment by ge1mina023** [comment]
> yes, you are running a test here - this isn't how a normal user would interact with nanos - if you're trying to run a program of your own I'd suggest using ops

Is this the correct feedback for the make run command？
