### ISSUE TITLE
boot on aws

### ISSUE THREAD

**Issue by eyberg** [nanovms/nanos#276]
https://www.cogini.com/blog/running-nerves-on-amazon-ec2/
https://www.freelists.org/post/rumpkernel-users/EC2-launch-script-feedback-valued
https://www.freelists.org/post/rumpkernel-users/Amazon-EC2-support-now-in-Rumprun
https://github.com/rumpkernel/rumprun/issues/68

https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/UserProvidedKernels.html

keep in mind that aws is transitioning from xen -> kvm

https://github.com/cloudius-systems/osv/issues/924.

**Comment by wjhun** [comment]
Resolved in #968
