### ISSUE TITLE
sendfile should support sending to any type of fd, such as a socket or pipe

### ISSUE THREAD

**Issue by wjhun** [nanovms/nanos#332]
The current sendfile implementation will only copy from one regular file to another. Rather, it should copy from any file descriptor to another, whether file, socket, pipe or something else. (Although, according to the man page, the input fd must be something mmap(2)-able, so not a socket...)

_Originally posted by @wjhun in https://github.com/nanovms/nanos/pull/280#issuecomment-451630228_

**Comment by eyberg** [comment]
I think this was fixed @wjhun ?

**Comment by wjhun** [comment]
This issue was made in error. The sendfile(2) manpage does say that the input fd must be a file that supports mmap(2) like operations, but for us that's just regular files at this point. Closing.
