### ISSUE TITLE
mmapped files aren't consistent - implement page fault handlers

### ISSUE THREAD

**Issue by convolvatron** [nanovms/nanos#34]
intitially we treat an mmap on a file as a read...we should (for some value of should), 

  - keep track of virtual regions (in the range tree)
  - allow registration of read and write handlers
  - wire up the read handler to demand-fill
  - wire up the write handler to stage a flush at some point (we want to
    window these to avoid doing a synchronized flush for every write)

**Comment by wjhun** [comment]
Resolved in various demand paging and pagecache work
