### ISSUE TITLE
Need to wait for init_virtio_network intialization

### ISSUE THREAD

**Issue by tijoytom** [nanovms/nanos#344]
Looks like http.get fails since there is no valid ip4 on the default adapter.The problem is that we don't wait for lwip callback (status_callback) to complete before en-queuing elf startup. It should be done like init_virtio_storage with a closure passed to status_callback and status_callback apply the closure to enqueue start method.

**Comment by francescolavra** [comment]
Detection and initialization of network interfaces is done synchronously, before starting the application. The DHCP client is also started before the application.
Waiting for an IP address from the DHCP server before starting the application doesn't sound right, the server may or may not be available when a VM is started, and its unavailability or network delays shouldn't prevent the VM from booting or delay the boot process.
Closing.
