### ISSUE TITLE
spring boot hello world

### ISSUE THREAD

**Issue by eyberg** [nanovms/nanos#479]
this is a pretty generic feature request - sorry

once we have java hello world working it'd be great to iron out anything to get spring/spring boot working - 
https://spring.io/guides/gs/spring-boot/

**Comment by briankoco** [comment]
#973 should get us there

**Comment by eyberg** [comment]
for anyone in the future that sees this 1.8 needs the tmp dir ->

```
{
  "Args": ["-Dos.name=Linux", "-jar", "/target/myproject-0.0.1-SNAPSHOT.jar"],
  "Dirs": ["target", "tmp"]
}
```
