### ISSUE TITLE
all go tests are currently trying to write to the same image file

### ISSUE THREAD

**Issue by eyberg** [nanovms/nanos#532]
there is no guarantee in which order go tests are ran and they are by default ran concurrently

**Comment by francescolavra** [comment]
Actually, go tests do not run in parallel by default. To enable parallel execution, a test function has to call `t.Parallel()`, and none of our test functions does that. So there is no risk of having different tests writing to the same image file at the same time. Closing

**Comment by eyberg** [comment]
maybe parallel is the wrong word but they most definitely run concurrently when invoked w/go test -> 

https://stackoverflow.com/questions/24375966/does-go-test-run-unit-tests-concurrently
