### ISSUE TITLE
svm warning msg appears on intel arch

### ISSUE THREAD

**Issue by eyberg** [nanovms/nanos#595]
warning flags for diff. architecture - i see this warning flag from time to time - afaik it's bitching about not finding amd here even though it's an intel box

```
eyberg@dungeon:~/gz$ lscpu  | grep Intel
Vendor ID:           GenuineIntel
Model name:          Intel(R) Xeon(R) Silver 4110 CPU @ 2.10GHz
```

```
qemu-system-x86_64: warning: host doesn't support requested feature: CPUID.80000001H:ECX.svm [bit 2]
```

is this is just a qemu warning msg or are we telling nanos to do something diff here? - for intel it should just be vmx

**Comment by francescolavra** [comment]
Most likely Qemu was trying to use acceleration when emulating an AMD processor. It should never happen now that Ops (as well as `make run` and `make test`) uses the `-cpu host` Qemu flag, which tells Qemu to emulate the same processor as the host processor.
In any case, this warning is generated at Qemu initialization, before the guest code is executed. Closing.
