### ISSUE TITLE
boot to digital ocean

### ISSUE THREAD

**Issue by eyberg** [nanovms/nanos#614]
i just tried uploading a raw disk for shits and grins and it seemed to accept it but didn't continue booting

this *looks* like it might be some low-hanging fruit and allow us to be multi-cloud out of the gate (plus there are a lot of devs that have side projects on do) - this def. looks way easier than aws at the moment and will require us to think about how deal w/diff. cloud deployments

**Comment by prologic** [comment]
As such a dev with side-projects utilizing DO's infra this would be nice to support soon :)

**Comment by eyberg** [comment]
this now works - i tried manually and works just fine (they allow you to upload raw disk images) - closing this issue in favor of adding the api glue to ops
