### ISSUE TITLE
Remove GCE hacks

### ISSUE THREAD

**Issue by mkhon** [nanovms/nanos#649]
Currently two GCE hacks exist:
- virtqueue is limited to 1 request, if this limit is removed GCE kills nanos VM with hostError error in StackDriver log
- MAX_IO_SIZE (offset_block_io) is set to 256k (should be PAGESIZE)

I suppose hostError happens because of interrupt handling latency. Need to get back to this once we are able to run with interrupts enabled.

Some work for that is in feature/io-enable-interrupts branch but I was not able to get rid of hostError.

**Comment by francescolavra** [comment]
> MAX_IO_SIZE (offset_block_io) is set to 256k (should be PAGESIZE)

This is now MAX_BLOCK_IO_SIZE (in kernel/init.c) and is set to 64k. Not sure why it was considered a hack, but I see no apparent reason was it should be PAGESIZE; in any case, this is not a GCP-specific setting.
