### ISSUE TITLE
implement a virtio balloon device driver

### ISSUE THREAD

**Issue by wjhun** [nanovms/nanos#660]
We have the means to reclaim freed/unused physical pages, so make them accessible to the virtio balloon device so that they become available for other VMs.

**Comment by eyberg** [comment]
saw this on the minios mailing list just now https://lists.xenproject.org/archives/html/minios-devel/2019-12/msg00215.html

**Comment by eyberg** [comment]
https://github.com/nanovms/nanos/issues/1079

**Comment by francescolavra** [comment]
Nanos currently supports virtio-balloon devices only when wired to the PCI bus; Firecracker doesn't have PCI, so its virtio-balloon devices are not PCI devices (they are most likely accessed via MMIO) and therefore not currently supported.
