### ISSUE TITLE
linode provisioning

### ISSUE THREAD

**Issue by eyberg** [nanovms/nanos#682]
this seems to suggest their setup is very close to gcloud's ->

https://www.linode.com/docs/platform/disk-images/kvm-reference/

**Comment by rouzier** [comment]
Are there any recent updates regarding supporting Linode?

**Comment by eyberg** [comment]
the last time I looked at this you had to deploy from an existing instance using dd so not only wasn't user-friendly but time-consuming and that's why it was skipped (practically every other integration we have is a simple image upload and then create instance from said image) - idk if they've changed their api at all since then 

https://www.linode.com/docs/guides/install-a-custom-distribution/
https://www.linode.com/products/linode-api/

**Comment by eyberg** [comment]
hrm -- looks like they *might*'ve changed things since then - so worth another look:

https://www.linode.com/products/images/
https://github.com/nanovms/ops/issues/470

**Comment by eyberg** [comment]
https://github.com/nanovms/ops/pull/1431

**Comment by eyberg** [comment]
now have basic image/instance creation support here - we can continue to add more in the future
