### ISSUE TITLE
cockroach tracking tkt

### ISSUE THREAD

**Issue by eyberg** [nanovms/nanos#850]
```
eyberg@dungeon:~/c/cockroach-v2.1.0.linux-amd64$ cat config.json
{
    "Args":["start", "--insecure"]
}

eyberg@dungeon:~/c/cockroach-v2.1.0.linux-amd64$ ops run -c config.json cockroach
Finding dependent shared libs
[start --insecure]
^[[Cbooting /home/eyberg/.ops/images/cockroach.img ...
qemu-system-x86_64: warning: TCG doesn't support requested feature: CPUID.01H:ECX.vmx [bit 5]
assigned: 10.0.2.15

panic: function not implemented

goroutine 1 [running]:
github.com/cockroachdb/cockroach/pkg/util/log.glob..func3(0x2ac6a1f)
        /go/src/github.com/cockroachdb/cockroach/pkg/util/log/stderr_redirect.go:25 +0xa3
exit status 5
```

https://github.com/nanovms/nanos/issues/832
https://github.com/cockroachdb/cockroach/blob/master/pkg/util/log/stderr_redirect.go#L19

**Comment by eyberg** [comment]
the other thing it's failing on is the missing statfs call

```
                        7 statfs
                        7 nosyscall statfs
                        7 gettimeofday
                        7 direct return: 0, rsp 0x70825ffb20
                        7 gettimeofday
                        7 direct return: 0, rsp 0x70825ffb20
                        7 write
*
* ERROR: failed to create resolver for: /cockroach-data: function not implemented
```

https://github.com/cockroachdb/cockroach/blob/69ef45027650a639c7845d44b576de98e1b3b4a6/pkg/cli/start.go#L348

https://github.com/cockroachdb/cockroach/blob/4a2aae60594a22aaf9675550fa362688983957c4/pkg/cli/flags_util.go#L430

**Comment by francescolavra** [comment]
With #1088, the symlink error is solved, but as @eyberg pointed out cockroach fails on the missing statfs call.

**Comment by francescolavra** [comment]
With #1091, it proceeds up to a point where it tries to create IPv6 sockets, which are currently not supported. Error message below.
```
ERROR: failed to start server: invalid --advertise-addr: lookup nanovms on [::1]:53: dial udp [::1]:53: socket: address family not supported by protocol
```

**Comment by eyberg** [comment]
cool!

w/this config ->

ops run -c config.json -p 26257 -p 26258 -p 8080 cockroach

```
{
  "Args":["cockroach", "start", "--insecure", "--advertise-addr=0.0.0.0"]
}
```

it gets around that but when using the client ``` ./cockroach sql --insecure```  I run into ```read tcp 127.0.0.1:54410->127.0.0.1:26257: i/o timeout``` almost immediately

**Comment by francescolavra** [comment]
With #1135, the issue is resolved.
In order to allow cockroach to properly initialize the DB when starting, I have to increase the file size of the image created by ops (e.g. with `truncate -s222m ~/.ops/images/cockroach.img`) and then launch Qemu manually.
In my PC, cockroach takes on average 30-40 seconds to initialize the DB.

**Comment by eyberg** [comment]
we have a pkg for this and w/the new mkfs fixes the truncate hack goes away
