### ISSUE TITLE
implement ftrace

### ISSUE THREAD

**Issue by eyberg** [nanovms/nanos#868]
need a way to profile/instrument to help find slowness

not sure if there's a callgrind lib that we could plug-n-play? or something like perf-kvm? if we don't have to code it that's great or if there are some super simple hacks that we could start getting some results from that would be good

**Comment by wjhun** [comment]
Implemented in #994 

@briankoco can we close this now?

**Comment by briankoco** [comment]
Some work remains on function_graph tracing, chunked http transfers, and perhaps tighter integration with trace-cmd/kernelshark, but basic support is now there
