### ISSUE TITLE
aws cloud-init

### ISSUE THREAD

**Issue by eyberg** [nanovms/nanos#877]
basic cloud-init support (we need to be able to do simple HTTP GET and parse the response in order to obtain IP address).

**Comment by wjhun** [comment]
Though there may be applications which still require cloud-init, we are able to boot on t2 and discover an IP using only DHCP.

**Comment by eyberg** [comment]
yeh this is more for user-level stuff of which I can't think of a use-case for right now - we can open again if we need to
