### ISSUE TITLE
inotify

### ISSUE THREAD

**Issue by eyberg** [nanovms/nanos#884]
seems the go implementation being used here uses epoll

https://github.com/fsnotify/fsnotify/blob/master/inotify.go#L38-L43

**Comment by francescolavra** [comment]
What is missing in the kernel is an implementation of the inotify API (which is a Linux-specific thing, see `man 7 inotify`), i.e. the inotify_init, inotify_init1, inotify_add_watch and inotify_rm_watch syscalls.

**Comment by am11** [comment]
Is an existing queuing mechanism in nanos suitable to implement inotify backend on?

**Comment by eyberg** [comment]
@am11 - is there a specific application you are looking at you'd like to use it for?

**Comment by am11** [comment]
In .NET world, one of the base class library (`System.IO.FileSystem`) uses inotify on Linux. There is, however, a fallback implementation behind an environment knob (`DOTNET_USE_POLLING_FILE_WATCHER=1 ./my-executable`), which uses file polling. I was wondering/hoping if this gets implemented, then we won't need to use fallback in nanos.

ps -the main implementation is based on pure inotify mechanism, without epoll overhead in the mix.

**Comment by francescolavra** [comment]
@am11 if I were to implement inotify in Nanos I would use the `notify_set` structure and the associated functions in https://github.com/nanovms/nanos/blob/master/src/unix/notify.h

**Comment by am11** [comment]
> i.e. the inotify_init, inotify_init1, inotify_add_watch and inotify_rm_watch syscalls.

@francescolavra, would it include these syscalls? `inotify_init`, `inotify_add_watch` and `inotify_rm_watch` is pretty much the surface area currently used by dotnet runtime (under `#ifdef HAVE_INOTIFY`): https://github.com/dotnet/runtime/blob/01b7e73cd378145264a7cb7a09365b41ed42b240/src/libraries/Native/Unix/System.Native/pal_io.c

**Comment by am11** [comment]
I can give it a try in next few days. :)

**Comment by francescolavra** [comment]
@am11 yes, at least inotify_init, inotify_add_watch and inotify_rm_watch would have to be implemented; inotify_init1 could be skipped.
