### ISSUE TITLE
AWS T2: bios_disk_read() hangs

### ISSUE THREAD

**Issue by mkhon** [nanovms/nanos#921]
stage2 bios_disk_read() hangs on AWS T2 (see screenshot)

![AWS T2 - BIOS boot](https://user-images.githubusercontent.com/3022749/61280379-f4ea8080-a7e1-11e9-8a48-dc010ee6daff.jpeg)

Observations:
- the same BIOS function (AH=42h) is used in stage1 (in real mode) to read stage2 and it works
- int 10h in stage2 (video output) works
- other int 13h functions (reset disk subsystem, get status) work
- I tried to reset disk subsystem (int 13h, AH=0) before doing disk read - does not help
- I tried to use other (legacy) BIOS CHS disk read function (AH=02h, build with NASMFLAGS=-DUSE_AH02) - also hangs
- grub does not seem to have this problem
- our ATA driver in PIO mode in stage2 works
- there is no such issue with Nitro-based instances (they boot properly)

The problem seems to be either in rather old BIOS used in T2 (based on Bochs BIOS SVN rev. 1.121) or their ATA controller implementation.

**Comment by wjhun** [comment]
I don't believe this issue has been resolved, but t2 boot is working using the ata routines in stage2. Not sure whether to re-open; it's not clear that we would need this as long as the ata support is there.
