### ISSUE TITLE
proper test for mmap(2), munmap(2), mremap(2), etc.

### ISSUE THREAD

**Issue by wjhun** [nanovms/nanos#936]
We need a runtime test to exercise the following syscalls in unix/mmap.c:

~~- mmap~~
~~- mincore~~
~~- munmap~~
~~- mremap~~
~~- mprotect (add to "paging" runtime test - which really should be called "page_prot" or something)~~

**Comment by briankoco** [comment]
- Partly addressed in #954 
- Still need mprotect test

**Comment by nsharma1231** [comment]
Hello! I'm a student from The University of Texas at Austin. My group and I, for our Virtualization class, are looking to contribute to an open-source repository and were looking to contribute to Nanos. Would we be able to work on this issue?

**Comment by eyberg** [comment]
sorry just now seeing this, yes please feel free to work on this, i'd just break up individual tests against the various data structures into separate pull requests, please reach out if you need more direction/help

**Comment by wjhun** [comment]
This issue hasn't been updated in some time. There is now an mmap test which has at least some level of testing for the above items. However, any improvements that can make the test be more thorough are welcome, so I'll leave it open for the time being.

**Comment by francescolavra** [comment]
Closed via #1334.
