### ISSUE TITLE
Is possible to move to other kernel or system?

### ISSUE THREAD

**Issue by letarg0** [nanovms/nanos#938]
I run my nanos on one machine. But if I stoping it my nanos move to other machine and still working. or if one kernel sleep other kernel work, my nanos walk to other kernel and working.

**Comment by eyberg** [comment]
i believe you are asking for live migration? or are you just asking for persistence? we do support persistence today; live migration should def be doable but we haven't really tested it, i'm not sure what you mean by 'move to other kernel' however - you can spin up multiple instances of the same image if that's what you are asking?

**Comment by eyberg** [comment]
closing for now - hope that answered the question
