### ISSUE TITLE
re-implement mincore(2)

### ISSUE THREAD

**Issue by wjhun** [nanovms/nanos#956]
The existing mincore(2) implementation was written before we had demand paging and has since bit-rotted. A new implementation could add a function to src/x86/page.c which uses traverse_entries() to act on each present page within a range (similar to zero_mapped_pages, but calling a closure passed from the outside the page table code), then calling said function with a mincore-specific closure (e.g. "mincore_page") to fill the vector as necessary.

**Comment by briankoco** [comment]
Addressed in PR #961
