### ISSUE TITLE
mremap(2) needs some work

### ISSUE THREAD

**Issue by briankoco** [nanovms/nanos#986]
Support is currently pretty limited. On the todo list are:
- support for targeted mappings via `MREMAP_FIXED`
- support for file-backed mappings (which should "just work")
- support for heap mappings (alloc'd via `brk` rather than `mmap`) and low memory/32-bit mappings (`p->virtual32`)
- support for remapping ranges that cover multiple adjacent mappings (currently we return `-EFAULT` if you specify a range that is fully mapped but straddles multiple vmaps, which technically seems permissible)

None of these are super critical at the moment I don't think, as we haven't seen anything that needs them, but they could crop up at some point and shouldn't be a major effort

**Comment by uma-sethuraman** [comment]
Hello, my team members and I are students at the University of Texas at Austin. We are interested in contributing to Nanos as a part of a project for our virtualization class. Is this issue still available for us to work on? Could we take on this issue?
